# Ethics {#ethics}

::: {.learning-goals}
🍎 Learning goals: 

* Distinguish between deontological, utilitarian, and virtue ethics approaches to research
* Identify key tenets of experimental vs. publication ethics
* Describe the ethical duty for transparency
:::

::: {.case-study}
🔬 Case study: Diederick Stapel
Dutch social psychologist, Diederick Stapel, was a research powerhouse; he authored and co-authored well over 200 articles on social comparison, stereotype threat, and discrimination and published his findings in dozens of prestigious journals  **[https://www.apa.org/science/about/psa/2011/12/diederik-stapel]**. It was Stapel who reported that affirming positive personal qualities buffered against dangerous social comparison, that product advertisements related to a person's attractiveness changed the manner and frequency with which they evaluated their own sense of self, and that exposure to intelligent in-group members boosted a person's performance on an upcoming task [@stapel2012; @trampe2011; @gordijin2012]. These findings were fresh and noteworthy at the time of publication; Stapel's papers were cited more than 11,000 times. The only problem? Much of Stapel's data were fraudulent.

When Stapel first began fabricating his data, he admitted to making small tweaks to a few cells in his data [@stapel2012b]. Changing a single number here and there would turn a flat study into an impressive one. Having achieved comfortable success (and garnering little suspicion from journal editors and others in the scientific community), Stapel eventually began altering entire data sets and passing them off as his own. But in 2011, several colleagues began to grow skeptical of his overwhelming success and brought their concerns to the Psychology Department at Tilburg University. Sure enough, his findings were, in fact, too good to be true. Stapel's dirty little secret had quickly become front-page news in the scientific community and his entire career was teetering on the brink of collapse. At the time of this textbook's release, 58 of Diederick Stapel's papers were **retracted**, or withdrawn from the journals they were originally published.

It might be tempting to conclude that Diederick Stapel's case was a highly unusual phenomenon, one that could never be duplicated. Unfortunately, scientific misconduct is more common than you might think. In fact, one recent study revealed that 1 in 12 Dutch scientists admitted to committing one or more serious forms of research misconduct [@devrieze2021]. What's more, nearly half of assistant and associate Dutch professors who completed a survey on research misconduct reported tampering with their data in the last three years. This is alarming for our field and illuminates the pervasiveness of the problem. Fortunately, you can decide to conduct honest and ethically-centered research. Don't fabricate your work. Do make an ethical commitment to research. In this chapter, we'll start discussing how.
:::

## Ethical Frameworks

In this section, we will discuss three ethical frameworks to guide our research pursuits. This is not meant to be an exhaustive list, and you are encouraged to consider other frameworks not mentioned here. 

### The Deontological Approach
If you were ever instructed as a child to "respect your elders", congratulations! You have been introduced to **deontological ethics**. Also known as duty-based ethics, deontology emphasizes the importance of morality in deed, regardless of the outcome [@Biagetti2020]. 16th century philosopher and Deontology's most cited figure, Immanuel Kant, believed that there exists universal moral laws everyone must obey, and that following these laws elevates us to rational agents. For example, The Ten Commandments, a biblical account in which the Jewish God (? is this the right way to word this) instructed his servant, Moses, to write down ten rules for the Israelite (? Israelite in the Bible, but better to say Israelis?) people to obey, is a prime example of deontological ethics   **[@English Standard Version Bible. (2001). ESV Online. https://esv.literalword.com/]**. Commands such as "Thou shalt not steal" and "Thou shalt not kill" offered clear instructions for the Israelite people to obey. To Kant, deontology provided a means of establishing order without the confusion of evaluating individual outcomes. This line of thinking is akin to prioritizing "intent" over "impact." It is important to remember that deontological ethics is unconcerned with individual needs, wants, desires, and goals, which means that morality is a function of both duty and action. Thinking back to our initial example that opened this paragraph, if we asked why we needed to respect our elders, we may have been told it was "the right thing to do."

Deontology is primarily concerned with four ethical tenets:

  (1) **Respect for autonomy**. This means that people participating in research studies can make their own decisions about their participation,         and that those with diminished autonomy (children, neuro-divergent people, etc.) should receive equal protections [@beauchamp2001].                Respecting someone's autonomy also means providing them with all the information they need to make an informed decision about their                participation in a research study without coercion. In short, we respect that people can make the best decision for themselves when provided       with the appropriate information related to that decision. 
  (2) **Beneficence**. This means that researchers are obligated (not simply suggested) to protect the well-being of participants for the duration       of the study. Beneficence is broken down into two actions based on writing from Greek physician, Hippocrates. The first is to do no harm.          Researchers must take steps to minimize the risks to participants and to disclose any known risks at the onset. If risks are discovered            during participation, researchers must notify participants of their discovery and make reasonable efforts to mitigate these risks, even if         that means stopping the study altogether. The second is to maximize potential benefits. This doesn't mean compensating                             participants with exorbitant amounts of money or gifts, it just means identifying all possible benefits and making them available where            possible. For example, a study that explores the impact of daily journaling on depressive symptoms in adolescents could maximize benefits by       inviting participants in the control or placebo conditions to also try journaling at the end of the study if it was shown to be effective at       reducing depressive symptoms. 
  (3) **Nonmaleficence**. This principle is similar to beneficence (in fact, beneficence and nonmaleficence were a single principle when they were       first introduced in the **Belmont Report**, which we'll discuss later) but differs in it's emphasis on doing/causing no harm. But remember,        deontology is about intent, not impact, so harm is sometimes warranted when the intent is morally good. For example, administering a vaccine       may cause some discomfort and pain, but the intent is to protect the patient from developing a deadly virus in the future. The harm is             justifiable under this framework. In social science research, we might ask participants to think about a painful memory or experience to           understand how emotions can be better regulated, which may temporarily bring discomfort and sadness but ultimately improve emotion research.
  (4) **Justice**. This means that both the benefits and risks of a study should be equally distributed among all participants. Justice can be           based on multiple criteria, including need, effort, contribution, and merit. In human subjects research we do not base justice on effort,          contribution, or merit because doing so would violate equal access to participation in research. This is also true in how participants are         assigned to study conditions. In general, participants should not be systematically assigned to one condition over another due to features         they arrive to the study with, like socioeconomic status, race and ethnicity, or gender. The caveat here is when there is sufficient evidence       or presumption that these factors affect people in systematic ways. Even then, distributive justice is of the utmost importance. 

This approach to ethics works well until it doesn't. Imagine you have a grandparent who says that people who don't wear seat belts should not receive medical attention if they are involved in an auto accident. What's more, your grandparent is on the local city council board and has decided to pass a city ordinance to prevent paramedics from assisting anyone suspected of not wearing their seat belt. Suddenly, you are faced with incompatible goals; although you have learned to respect your elders, you also believe that people who are involved in auto accidents deserve medical attention, regardless of whether or not they were wearing a seat belt at the time of impact. Deontological ethics deals only in absolutist terms, meaning that there exists one set of standards to follow and that there can be no gray area. Deontology cannot solve your complicated moral dilemma, and you are no closer to arriving at a solution.

### The Utilitarian Approach
Now imagine you feel so strongly about this issue of who should receive medical attention during an auto accident that you cannot help but speak up to your grandparent and attempt to change their mind. While you respect their opinion, you are disappointed by their decision and plan to express this disappointment. How do you reconcile a moral obligation to respect your elders with a separate moral obligation to support the well-being of others? In this case, you might consider a utilitarian approach. **Utilitarian ethics** emphasizes an action's outcome as the marker for whether or not to engage in that action [@flinders1992]. Particularly, utilitarianism asks whether the greatest number of people receive the greatest benefit from some action. If yes, proceed. If no, consider alternative solutions that maximize positive outcomes for more people. 

Utilitarian ethics as we have come to understand it today was heavily influenced from work by John Stuart Mill, a 19th century British philosopher and economist. Mill likened utilitarianism to something called the **Greatest Happiness Principle**, or the idea that an action should be considered morally good based on the degree of happiness or pleasure people experience because of it, and that an action should be considered morally bad based on the degree of unhappiness or pain people experience by the same action [@mill1859]. When Mill wrote the book, *Utilitarianism*, many of his critics challenged this idea that pleasure could adequately define morality because it was considered subjective and, by extension, impractical. In response, Mill (thoroughly irritated by his colleagues' 'simple-mindedness') concluded that most humans would converge on the same maximally pleasurable and "noble" actions, even if some community members would seek pleasure in actions that offer the potential of harm to others. To these critics, he writes, "utilitarianism...could only attain it's end by the general cultivation of nobleness of character, even if each individual were only benefited by the nobleness of others, and his own, so far, as happiness is concerned, were a sheer deduction from the benefit." In other words, utilitarianism works in societies where most people seek pleasure in actions that cause little or no harm to others. In the case of your grandparent, utilitarian ethics would support your decision to speak out against an ordinance that harms some victims of auto accidents.

By this point, you might have some healthy doubts about pursuing a utilitarian framework, even in our imaginary example about your grandparent and victims of auto accidents. You might be thinking, "What if I live in a community of people with more mixed or, worse, more harmful views?" Utilitarianism is based on an assumption that people are generally good and that actions which bring about the most pleasure are generally positive. Essentially, it relies on a "majority rules" policy to function successfully. This is a reasonable approach when a community is relatively homogeneous in thinking or when the action is popular among most people. But as you may have gathered by now, a utilitarian framework is ineffective when actions bring about mixed feelings or when there is significant disagreement of individual goals. Although Mill was confident that societies would converge on moral outcomes, we must also take into account what effects the minority community members may face under utilitarianism. "Casualties" are inevitable when the focus is on the greater society, but the means justify the ends [@garbutt2011]. Given what we've discussed so far, what viable alternatives are out there? 

### The Virtue Approach
Another way we can approach this ethical dilemma is through a virtue framework. You have probably heard the phrase, "patience is a virtue" more than you care to remember, and that is probably because we have cared a lot about virtues for a very long time. From Aristotle to Voltaire, Churchill to Baldwin, and many others in between, we place a premium on virtuous actions. Before we dive any further, let's first discuss what we mean by virtue. A **virtue** is a trait, a disposition, or a quality that is thought to be a moral foundation [@annas2006]. Someone who regularly collects and hands out coats to refugees in their community may be thought of as having a virtue of compassion while someone else who always seeks to tell the truth no matter the consequences may be thought of as having a virtue of honesty. These virtues are both learned from and revered by a society, which only reinforces their importance. 

One essential feature of virtue ethics is that people can learn to be virtuous by observing those actions in others they admire [@morris2016]. Proponents of virtue ethics say this works for two reasons: (1) people are generally good at recognizing morally good traits in others and (2) people receive some fulfillment in living virtuously. This is different from utilitarianism because it focuses on the actions and character of the person rather than on the consequences the action brings to the majority of society. Let's return to the auto accident example we discussed earlier to illustrate this idea. How would you approach your grandparent about their views of victims of auto accidents under this ethical framework? If you want to think like a virtue theorist, you might consider the question, "What do I need to do to lead a good life?" If what matters to you are virtues of compassion and kindness, you will share your disappointment with your grandparent's decision and will challenge the city ordinance they put in place. But if you value honor and respect above all else, you might decide not to speak up in this case. Are you seeing the difference now? Virtue ethics emphasize the goals of the individual and relies on peoples' desires to do the "right" thing as they see it.

It might be easy to see the potential downsides to this framework when we think about the variety of goals that drive our decisions. No clearer do we see these differences than in the American political context. American politics is primarily divided into two parties- Democratic (typically liberals) and Republican (typically conservatives). These two political parties have become more polarized over the last four decades, not because one party is a bad apple but because the virtues that drive decision-making within these parties have become more distinct. Political debates are primarily concerned with one or more of five moral foundations- care (where the goal is to reduce suffering), fairness (where the goal is to improve equality), loyalty (where the goal is to support in-group members), authority (where the goal is to respect leadership and tradition), and sanctity (where the goal is to promote purity) [@feinberg2019; @graham2009]. Whereas conservatives tend to value loyalty, authority, and sanctity, liberals have been shown to value care and fairness virtues. Because both parties have placed importance on differing virtues, party members approach policy decisions from the lens of the virtues they value. So which side is right? According to virtue ethics, they both are. So long as party members uphold values most important to them, all is right with the world.

### Optimal Ethical Framework for Human Subjects Research

## Experimental Ethics

### The IRB
Over one decade after surviving prisoners were liberated from the last concentration camp of the Holocaust, Adolf Eichmann, one of the Holocaust's primary organizers and leaders, was tried for the role he played in this ghastly extermination crusade [@baade1961]. Eventually known as the Eichmann Trial, this 8-month-long investigation led to 15 counts of criminal offenses, including crimes against the Jewish people and crimes against humanity. While reflecting on his rationale for forcibly removing, torturing, and eventually murdering millions of Jews under the direction of Adolf Hitler, an unrepentant Eichmann claimed that he was "merely a cog in the machinery that carried out the directives of the German Reich" [@kilham1974], that he was not directly responsible for the millions of lives taken. This startling admission gave a young assistant professor at Yale University an interesting idea. He thought to himself, "Could it be that Eichmann and his million accomplices in the Holocaust were just following orders? Could we call them all accomplices?" [@milgram1974]. That young professor was Stanley Milgram, and the (in)famous Milgram experiment was born.

To test whether people would comply under the direction of an authority figure no matter how uncomfortable or harmful the outcome, Milgram invited participants into the laboratory to serve as a teacher for an activity [@milgram1963]. Participants were told that they were to administer electric shocks of increasing voltage to another participant, the student, in a nearby room whenever the student provided an incorrect response. In reality, the student was a confederate who was in on the experiment and only pretended to be in pain when they received the shocks. Participants were encouraged to continue administering shocks despite clearly audible pleas from students to stop the electric shocks. Milgram predicted that only about 1% of participants would continue until they had delivered the maximum voltage. The results were shocking; 65% of participants administered the maximum voltage to the student, and displayed anxiety symptoms, nervousness, and some even developed seizures. Although experimenters debriefed participants at the end of the study, the damage had already been done. Milgram's shocking shock experiment convinced many people in the scientific community to adopt stricter policies that protect study participants from unnecessary or incongruent harm as had been observed in this experiment.

Unfortunately, Milgram's shock experiment was just one of dozens of unethical human subjects studies that garnered the attention (and anger) of the public. Something had to be done. In 1978, the National Commission for the Protection of Human Services of Biomedical and Behavioral Research released **The Belmont Report**, a 20-page document outlining protections for the rights of human subjects participating in research studies [@adashi2018]. Perhaps the most important message found in the Report was the notion that "investigators should not have sole responsibility for determining whether research involving human subjects fulfills ethical standards. Others, who are independent of the research, must share the responsibility." In other words, ethical research required both transparency and external oversight. Whereas much of the research being done before the release of the Belmont Report modeled a utilitarian framework, commissioners were adamant that this approach was both unethical and self-serving. The days of exploitative and rogue human subjects research were dwindling quickly. 

A by-product of the Belmont Report, and of calls to reform biomedical and behavioral research involving human subjects, was the creation of the **Institutional Review Board**, or the **IRB**. The IRB is a committee of people who review, evaluate, and monitor human subjects research to make sure that participants' rights and agency are protected when engaging in research [@oakes2002]. You can think of the IRB as a local government, and every organization that conducts human subjects or animal research is required to have an IRB. Your university likely has an IRB, and its members are probably a mix of scientists, doctors, professors, and community residents. When a group of researchers have a research question they are interested in pursuing with human subjects, they must receive approval from their local IRB before beginning any data collection. The IRB reviews each study to make sure:

  (1) A study poses **minimal risk** to participants. This means the anticipated harm or discomfort to the participant is not greater than what          would be experienced in everyday life. Because participants in Milgram's experiment experienced heightened anxiety and seizures, it would not       have passed the minimal risk assessment.
  (2) Researchers obtain **informed consent** from participants before collecting any data. This means experimenters must disclose all potential         risks and benefits so that participants can make an informed (Get it?) decision about whether or not to participate in the study.                  Importantly, informed consent does not stop after participants sign a consent form. If researchers discover any new potential risks or             benefits along the way, they must disclose these discoveries to all participants.
  (3) All collected information remains confidential. **Confidentiality** is critical, especially when collecting protected health information (or       **PHI**). For the most part, what happens in the lab stays in the lab. Researchers have an obligation to their participants to protect their       names, addresses, and social security numbers at minimum. Data that is anonymized and encrypted is harder to land in the wrong hands. While        researchers cannot guarantee confidentiality, we can (and should) minimize the risk wherever possible. We'll talk more about this in a later       section.
  (4) Participants are recruited equitably and without coercion. Before the IRB became a standard oversight, researchers often utilized                  marginalized and vulnerable populations to test their research questions, and these questions sometimes required extremely invasive                procedures. We'll discuss what we mean by marginalized and vulnerable populations in the Special Considerations for Vulnerable Populations         section. For now, you should know that participation in research studies should always be made voluntary and that everyone eligible to             for a study should have equal access to participate.  

Did you know that the IRB operates under one of the three ethical frameworks we discussed in the last section? Based on what you've learned so far, take a moment to guess which framework the IRB has adopted (no peeking!). If you guessed deontological, you're right. Remember that deontologists are concerned with the intent over the impact of an action. We do not steal because stealing is wrong. We can see a deontological IRB in action when we consider how they make decisions. One of the IRB's primary oversights is ensuring the autonomy of participants, and they do this by following a strict set of guidelines. This rule-based approach to ethics is paramount to deontology 

<p> Proposed framework: virtue </p>
<p> Navigation </p>

### Debriefing Participants
So far, we've discussed one research study that prompted external oversight and additional scrutiny of human subjects research. But before the shock experiments was the Tuskegee Syphilis Study, and the results were even more devastating and egregious. In 1929, The United States Public Health Service (USPHS) was perplexed by the effects of a particular disease in its latent form that seemed to find its local epicenter in Macon County, Alabama, with an overwhelmingly Black population [@brandt1978]. Syphilis is a sexually transmitted bacterial infection that can either be in a visible and active stage or in a latent stage **[@cite]**. At the time of the study's inception, roughly 36% of Tuskegee's adult population had developed some form of syphilis, one of the highest infection rates in America [@white2006]. Thanks to a grant from the Julius Rosenwald Fund and leadership from Dr. Taliaferro Clark and Surgeon General H.S. Cumming, the USPHS recruited 400 Black males from 25-60 years of age with latent syphilis and 200 Black males without the infection to serve as a control group to participate in what would become one of the most exploitative research studies ever done on American soil [@brandt1978]. The USPHS sought the help of the Macon County Board of Health to recruit participants with the promise that they would provide treatment for community members with syphilis. The researchers sought poor, illiterate Blacks and, instead of telling them that they were being recruited for a research study, they merely informed them that they would be treated for "bad blood", a phrase used in that time to refer to syphilis. But because the study was only interested in tracking the natural course of latent syphilis without any medical intervention, the USPHS had no intention of providing any care to its participants. To assuage participants, the USPHS distributed an ointment not been shown to be effective in the treatment of syphilis, and only small doses of a medication actually used to treat the infection. In addition, participants underwent a spinal tap which was presented to them as another form of therapy and their "last chance for free treatment." By 1955, just over 30% of the original participants died from syphilis complications. Dr. O.C. Wenger of the disease clinic in Hot Springs, Alabama, admitted, "we now know, where we could only surmise before, that we have contributed to [the participants'] ailments and shortened their lives." But even this admission did not mark the end of the experiment. In fact, it would be another 22 years before the final report was released and (lack of) treatment ended. In total, 128 participants died of syphilis or complications from the infection, 40 wives became infected, and 19 children were born with the infection [@katz2011]. The damage rippled through two generations, and many never actually learned what had been done to them. 

Think critically about what went wrong with the Tuskegee Syphilis Study. In what ways did investigators violate the rights of participants? Let's start from the beginning. Investigators did not obtain informed consent. Participants were not made aware of all known risks and benefits involved with their participation. Instead, they were led to believe that diagnostic and invasive exams were directly related to their treatment. In human subjects research, this is referred to as **deception**. A study is deceptive when (1) experimenters withold any information about its goals or intentions, (2) experimenters hide their true identity (such as when using a confederate), (3) some aspects of the research are under- or overstated to conceal certain information, or (4) participants receive any false or misleading information [@tai2011]. Deception is harmful to participants because it prevents them from making an informed decision about their involvement in a research study. In the case of the Tuskegee Syphilis Study, participants were unable to decline participation on the basis that they would not actually receive treatment. Had the men involved in the study known this fact, it is unlikely all 299 with the infection would have remained enrolled. Additionally, participants were denied appropriate treatment following a 1943 discovery that penicillin was effective at treating syphilis [@mahoney1943]. In fact, the USPHS requested that medical professionals overseeing their care outside of the research study not offer treatment to participants so as to perserve the study's integrity. This intervention violated participants' rights to equal access to care, which should have taken precedence over the results of the study. Another problem with this research study was that recruitment was both imbalanced and coercive. Not only were participants selected from the poorest of neighborhoods in the hopes of finding vulnerable populations with little agency, but they were also bribed with empty promises of treatment and a monetary incentive to pay for burial fees, a financial obstacle for many sharecroppers and tenant farmers at the time. 

Importantly, the USPHS failed to **debrief** the men involved in their study. What does it mean to debrief participants about a research study? In general, deception in scientific research is considered unethical because it misleads the participant on their assumptions about how they will be involved in a study. But sometimes deception is necessary. Consider a recent study led by researchers at Northwestern University and The University of California at Berkeley who were interested in understanding how people regulate emotions after experiencing loss [@rompilla2021]. Rather than finding people who had actually experienced recent loss, researchers instead asked older adults to watch short clips that depicted some type of loss in order to artificially induce these feelings. Once researchers invoked these feelings, they then exposed participants to different means of reappraising these emotions. Do you remember what the goal of the study was? It certainly wasn't to make people sad, but instead to determine how different forms of emotional reappraisal alleviate the negative emotions associated with loss. The researchers needed these feelings to be readily accessible to participants in order to adequately evaluate the reappraisal strategies of interest. They also needed to debrief, or to inform participants about the deception and reveal the true study goals [@tai2012]. A critical piece of the debriefing process is soliciting participant thoughts and attitudes about any deception involved. Why might it be important to gather this information? We should be cognizant of the potential effects that our deception has on our participants. For Rompilla and colleagues (2021), it would be important to know whether participants had any lingering and unresolved negative emotions at the conclusion of the study and to talk through these feelings before releasing participants back to their regular lives.

Debriefing should happen at the end of any research study, even if the level of deception appears low. This hard-and-fast rule removes researcher-interpretation about the distinctions between high and low deception. Imagine running a study in which you are curious about the relationship between children's developmental language trajectory and how often parents talk to their children. To do this, you record parent-child interactions in a lab setting and then have children complete a word recognition task over several time periods. To preserve parents' natural communication tendencies with their children, you may not want to reveal exactly what you are studying at the first appointment. It would be reasonable to wait until the last interaction to share your intentions with parents so long as (1) doing so does not pose additional risks or harm to participants and (2) you have received expressed approval from the IRB [@tai2012]. This also means you may not skip this step or assume participants know your intentions. Remember the ethical principle of justice we discussed earlier in this chapter? It also applies to debriefing! Every participant should have equal access to study information regardless of how the experimenter views the deception. 

Now that we have established both the function and importance of debriefing, let's discuss strategies on how to effectively debrief participants. In general, debriefing is composed of four parts: (1) participation gratitude, (2) discussion of goals, (3) explanation of deception, and (4) questions and clarification [@allen2017]. In the following sections, we will unpack each component in further detail.

#### Participation Gratitude
It is generally a good idea to thank participants for their involvement in the research study, especially because research participation is completely voluntary. Sharing your gratefulness for participation can be as short and as simple as, "Thank you so much for participating in the research study today." Some studies also include an additional token of appreciation such as monetary compensation or course credit (this is typically used in undergraduate settings). If monetary or other physical compensation will be implemented, it should be commensurate with the amount of time and effort required for participation. A study that includes 2 hours of fMRI scanning and a battery of reaction time measures is probably undervaluing participant involvement when offering \$5 at the conclusion of the study, but another study that is offering \$ 100 for completing a 5-item questionnaire is probably overvaluing participant involvement. If you're having trouble deciding how to compensate participants in your research study, try gathering data about compensation structures for similar studies. Your institution's IRB office may also have insights about how best to compensate research participants. Remember, the most important point of this component is that you've appropriately communicated your gratitude to your research participants.

#### Discussion of Goals
Next, researchers should briefly share the purpose of the research study with participants. Why were participants recruited for this study in the first place? What are the researchers hoping to learn by conducting this study? It is important to ensure that participants fully understand the goals of the study, so avoiding technical jargon or confusing language is critical. One question you might have at this point is how much information is necessary to disclose to participants. There is no exact formula but participants should generally know about the research questions and hypotheses. As an added bonus, you might also consider sharing any preliminary findings or where to find the completed write-up at the study's conclusion. This latter point may be useful when some aspect of the study appears evaluative and participants are interested in knowing how well they preformed against their peers. For example, a parent whose child completed a word-recognition task may request information about their child's performance. Importantly, many studies cannot evaluate individual data points because they are only meant be informative in the aggregate so providing information about a single data point is futile at best and risky at worst. Instead of offering information about the individual child, a researcher might choose to share preliminary results about the entire data set or agree to follow up with the parent when the data has been published.

#### Explanation of Deception
Before concluding involvement in the research study, participants should be aware of whether and how any deception was utilized, regardless of how minor the deception seems to the researcher. David Holmes referred to this component of the debriefing process as **dehoaxing** because it is meant to illuminate any aspects of the study that were previously misleading or inaccurate [@holmes1976]. The goal here is two-part: (1) to reveal the true intent of the study and (2) to alleviate any potential anxiety associated with the deception. After identifying where the deception occurred, it is useful to explain why the deception was necessary for the study's success. Then, researchers should clarify any misconceptions brought about by the false information. For example, researchers who administer a pill meant to increase confidence before participants are told they will give a speech in front of a large crowd should reveal that the pill was merely a placebo which has no effect on confidence levels or on performance. In this case, participants should not leave with the impression that taking a pill will improve their public speaking skills. Although it is still possible that participants could have some residual uncertainty about whether or not a study was truly deceptive, it is important that researchers clearly communicate points of deception and attempt to correct any misinformation at the study's conclusion.

#### Questions and Clarification
Finally, researchers should answer any questions or address any concerns raised by participants. Many researchers use this opportunity to first ask participants about their interpretation of the study, what they thought were the study goals. This not only illuminates aspects of the study design that may have been unclear to or hidden from participants, but it also begins a discussion where both researchers and participants can communicate about this joint experience. This step is also helpful in identifying negative emotions or feelings resulting from the study [@allen2017]. When participants do express negative emotions, researchers are responsible for sharing resources participants can utilize to work though the discomfort. Resources may include information about mental health services, hotlines, or contact information for the study's principal investigator or the office of the IRB that approved the study. This also means that participants maintain the right to report any concerns they have about the study beyond the research team, and this right does not disappear once individual participation has concluded. Thus, it is important that researchers reiterate that participation in the study is voluntary and that participants have the right to withdraw at any time. If researchers cannot adequately answer participant questions, they should refer participants to entities who can. 

#### A Note on Debriefing in Online Studies
With the widespread proliferation of data collection sites such as Amazon Mechanical Turk and Prolific, many researchers have elected to conduct some or all of their studies online. Online studies can be advantageous to the research landscape because they increase sample diversity and access to science. A research lab located in the western United States who recruits participants for in-person testing may achieve some impressive diversity when advertising in libraries and grocery stores, but can almost certainly increase its scope when recruiting participants across the country. This also means that people who are unable to travel to research sites but have reasonable access to a computer with internet capabilities are suddenly able to contribute to the scientific community in ways previously unimaginable. But with this new landscape comes new considerations for researchers, especially in the ethical domain. So far in this chapter, we have discussed strategies for conducting ethically mindful research in in-person settings, but what is still outstanding is how to transfer these new skills online, namely when debriefing participants. Fortunately, this process is easier than you might think. Importantly, debriefing is required regardless of the study's presentation method. When a study is fully automated and participants do not interact with experimenters, researchers can make use of **debriefing statements**. Debriefing statements are documents that summarize all four components of the debriefing process (participation gratitude, discussion of goals, explanation of deception, and questions and clarification). Because experimenters are not present at the end of the study to answer participant questions, the statement typically provides the contact information for both the principal investigator and the IRB office. These communication channels should be clearly conveyed should participants need to follow up about the study for any reason. It might also be worth considering whether a study is best suited for the online space given its content. Studies that have high deception levels or induce negative emotions/are triggering in nature may benefit from having an experimenter present to verbally alleviate concerns and adress points of deception rather than relying on a written statement. If researchers cannot be reasonably sure that participants will not receive any additional benefit in speaking with an experimenter following their involvement in the study, it is worth reconsidering whether the study can be conducted online in the first place.

### Special Considerations for Vulnerable Populations
Regardless of who is participating in research, investigators have an obligation to protect the rights and well-being of all participants. However, some populations have been designated as vulnerable and should receive additional considerations or oversight when involving them in research studies. In this section, we will consider four of a handful of vulnerable populations and discuss whether and how to include them in research studies.

#### People with Disabilities
There are thousands of disabilities that affect cognition, development, motor ability, communication, and decision-making with varying degrees of interference, so it is first important to remember that considerations for this population will be just as diverse as its members. Officially, a disability is a diagnosed mental or physical condition that limits or restricts a person's involvement in daily activities [@stineman2001]. Roughly 8% of the US population is disabled, which makes it likely that, in the context of a research study, researchers may come into contact with someone who is disabled. Assuming all general rules and regulations are followed, there are no laws that preclude people with disabilities from participating in research. However, those with cognitive disabilities who are unable to make their own decisions (importantly, this also applies to children with or without disabilities) may only participant with written consent from a legal guardian and with their individual assent (if applicable). This means that even if the person provides assent, researchers may not enroll them in the research study without also obtaining consent from their guardian. Those retaining full cognitive capacity but who have other disabilities that make it challenging to participate normally in the research study should receive appropriate accommodations to access the material, including the study's risks and benefits. Imagine 


<p> Crowd workers </p>
<p> Low-income families </p>
<p> Prison population </p>

::: {.ethics-box}
🌿 Ethics box: Countering institutional injustice in the inclusion of marginalized populations (Walsh and Ross 2003; Noguera 2003). Example: representation of Black boys in research on aggression in childhood.
:::

## Publication Ethics

### Authorship
<p> Why it matters/saving yourself the trouble </p>
<p> When to have the conversation </p>
<p> When to re-evaluate </p>

### Disclosures
<p> Why it matters </p>
<p> Financial statements </p>
<p> Conflicts of interest </p>

### Generalizability Statements
<p> Purpose and why it matters </p>
<p> Important elements </p>
<p> Example statement </p>

### Post-publication Errors
<p> Don't ignore it! </p>
<p> How to remedy it </p>
<p> Why it matters </p>

### Intellectual Humility

::: {.accident-report}
⚠️ Accident report: Is it ethical to “cherry pick” research? Simmons, Nelson, & Simonsohn (2011) experiment shows that listening to the Beatles actually makes you younger!
:::

## The Ethical Duty for Transparency

Openness is definitional to the scientific enterprise. @merton1979 described a set of norms that science is assumed to follow: communism – that scientific knowledge belongs to the community; universalism – that the validity of scientific results is independent of the identity of the scientists; disinterestedness – that scientists and scientific institutions act for the benefit of the overall enterprise; and organized skepticism – that scientific findings must be critically evaluated prior to acceptance. The choice to be a scientist constitutes acceptance of these norms.

For individual scientists to adhere to these norms, the products of research must be open. To contribute to the communal good, papers must be available so they can be read, evaluated, and extended. And to be subject to skeptical inquiry, experimental materials, research data, analytic code, and software must be all available so that analytic calculations can be verified and experiments can be reproduced. Otherwise, evaluators must accept arguments on the authority of the reporter rather than by virtue of the materials and data, an alternative that is inimical to the norm of universalism. For many scientists, the situation is neatly summarized by the motto of the Royal Society: “Nullius in verba,” often loosely translated as “on no one’s word”.

Beyond its centrality to science, openness also carries benefits, both to science and to scientists. Open access to the scientific literature increases the impact of publications, which in turn increases the pace of discovery. Openly accessible data increases the potential for citation and reuse, and maximizes the chances that errors are found and corrected. These benefits accrue not just to the scientific ecosystem at large but also to individual scientists, who gain via citations, media impact, collaborations, and funding opportunities. 

Some responsibilities follow from these benefits. Because openness maximizes the impact of research and its products, researchers have a responsibility to their funders to pursue open practices so as to seek the maximal return on funders’ investments. And by the same logic, if research participants contribute their time to scientific projects, the researchers also owe it to these participants to maximize the impact of their contributions [@brakewood2013].

For all of these reasons, individual scientists have a duty to be open – and scientific institutions have a duty to promote transparency in the science they support and publish.

### The negatives of openness

Scientists have many other ethical duties beyond openness, however. They have obligations to their collaborators and trainees. They have committed to funders to complete specific studies. And in biomedical and social science fields, they have duties to preserve the welfare of their research participants as well. Conflicts with these duties are often the source of researchers’ hesitance to embrace openness. 

Transparency policies also carry costs in terms of time and effort. For example, some routes to open access publication require authors to pay substantial publication costs (i.e., author processing charges). Organizing materials and data for sharing as well as providing support to dataset users can also be time-consuming, especially for larger datasets. 

Maintaining participant confidentiality is a major source of both cost and risk for biomedical and other human subjects research. Loss of confidentiality by research participants can have big negative consequences for health, employment, and well-being. While ensuring that tabular data does not contain identifying information is often relatively straightforward, other types of data can be tricky and expensive to anonymize. For example, removing identifying information from video data requires considerable time and expertise. And certain types of dense or narrative data simply may not be de-identifiable due to aspects of the data or the participants’ identities. 

Transparency can even be a source of risk – actual or perceived – to researchers themselves. Effort spent pursuing open practices may not be seen as compatible with other career incentives. For example, learning technical tools to facilitate code and data sharing could take away from time to pursue new research. Disclosure of high value datasets prior to publication could in principle lead to opportunities for “scooping” – though it turns out that there are very few documented cases of pre-emption as a result of data sharing. Finally, open sharing of research products prior to and during peer review might carry greater risk for junior researchers and for researchers from disadvantaged groups, because of their greater vulnerability to critiques or negative attention.

### Individuals should consider openness as a default

In the face of competing duties as well as potential negatives to openness, what should individual researchers do? First, because of the ethical duty to openness for every scientist, open practices should be a default in cases where risks and costs are limited. For example, the vast majority of journals allow authors to post accepted manuscripts in their untypset form to an open repository. This route to “green” open access is easy, cost free, and – because it comes only after articles are accepted for publication – confers essentially no risks of scooping. As a second example, the vast majority of analytic code can be posted as an explicit record of exactly how analyses were conducted, even if posting data is sometimes more fraught. These kinds of “incentive compatible” actions towards openness can bring researchers much of the way to a fully transparent workflow, and there is no excuse not to take them.

For some researchers, however, there will be real negatives associated with one or more open practices. If they are not aware of the positive benefits of transparency and sharing for their work and the work of their trainees, they may consider open practices only as a necessary evil, rather than as opportunities to increase citations or build a reputation. But if they recognize the potential benefits of openness, researchers can ask whether there are steps that can be taken to realize some of those benefits while mitigating risks – for example, releasing only summary, tabular data rather than raw media data, or making use of a data sharing repository with robust access control.

In some cases, researchers might decide not to share. One example of this kind of situation came up in my own work, when I was studying dense audio-video recordings of the private life of a single identified family; these data are both sensitive and impossible to de-identify. The family decided not to share these data, and I support this decision, having seen how much the data would have compromised their family's privacy – though we did make tabular data available so that statistical results could be reproduced. A second more general case is archival data without consent for sharing where recontacting participants may be impossible or impractical. These cases are relatively rare, however; it is more common that sharing simply presents some potentially mitigable costs. It is precisely in these cases that institutions should step in.

### Institutions can mitigate the risks and costs of openness

Given the ethical imperative towards openness, institutions like funders, journals, and societies need to use their role to promote open practices and to mitigate potential negatives. Scholarly societies have an important role to play in educating scientists about the benefits of openness and providing resources to steer their members towards best practices for sharing their publication and other research products. Similarly, journals can set good defaults, for example by requiring data and code sharing except in cases where a strong justification is given (equivalent to adopting the second highest level in the Transparency and Openness Promotion guidelines). I don't think the TOP guidelines are perfect, but I'm not sure why in this case we'd let the perfect be the enemy of the good.

Departments and research institutes can also signal their interest in open practices in job advertisements and tenure/promotion guidelines. We did this the last time we had a search at Stanford Psych and it signaled our department's general interest in these practices, leading to some good conversations with candidates (and letting us notice explicitly if candidates weren't as interested as we were). In addition, by structuring graduate programs to provide training in tools and methods for data and code sharing, departments can educate grad students about producing reproducible and replicable research – this has been my hobby horse for quite a while (see here and here). 

Institutional funders of research play the most important role, however. Most funders already signal an interest in openness through a required data management plan or similar document, and some (like the US NIH) mandate data sharing to the extent permissible given other regulatory constraints (e.g., institutional review, health or data privacy laws). These requirements, though laudable, don't really change the scientific incentives at play. Data sharing should not just be required: It should also be treated as part of the scientific merit of an application. Creating a sufficiently high value dataset should be itself meritorious enough to warrant funding. And on the opposite side of the calculus, funders should signal their willingness to support the effort required to mitigate data sharing costs. For example, this could take the form of extra budget supplements explicitly tied to sharing activities. 

More generally, funders and other institutional stakeholders need to act to change the incentive structure for individuals. For example, funding agencies could make it a priority to invest in creating technical tools and practice guidelines for human subject data anonymization. A small RFP for these could create huge value, making it much more straightforward to participate in data sharing. 

### Conclusion

Both advocates and critics of open practices often appear to be arguing about the merits of radical transparency, but this goal is often not achievable. Instead, individual researchers and institutions should proceed from both an understanding of the benefits of openness and an appreciation of the ethical duty to be open. These starting points lead naturally to a set of practices that are open by default, with exceptions in case of specific risks. 

When individual researchers can't mitigate the costs associated with openness, responsibility falls to institutional actors in the scientific ecosystem to help. We can all do our part in this by lobbying our journals scientific societies, institutions, and funders to support researchers in making the right decisions around transparency.