# Statistical models {#models} 

::: {.learning-goals}
🍎 Learning goals: Describe what it means to ‘control for’ something; explore what kinds of ‘clustered variance’ are present in our designs (e.g. selecting appropriate fixed vs. random effect structures); select models appropriate for different kinds of dependent variables.
:::

::: {.case-study}
🔬 Case study: Sometimes effects are driven by specific stimuli. The “language as fixed effects fallacy” (Clark, 1973) means that many early psycholinguistic effects didn’t take into account stimulus variability. This critique extends to a wide variety of other domains, e.g. task fMRI (Westfall, Nichols, and Yarkoni 2016).
:::



## Inference and estimation for two-group designs

Throughout this book we've taken the position that the goal of experiments is to estimate a causal effect of interest, ideally as part of some theory of how different constructs relate to one another. All this talk of hypotheses and inferences above is only indirectly related to that goal. 





- Intuition builder: For very large n, or flat prior, Bayes and frequentist coincide. 


### Simple models of between-group differences

Introducing simple inference models:

- The chi-squared test for inferring whether two samples come from the same distribution
- The t-test for inferring whether a single group’s effect differs from 0
- The t-test for inferring whether two groups differ from one another
- The paired t-test as a first glimpse at how we might account for participant-level random effects (see Chapter 7).


::: {.accident-report}
⚠️ Accident report: Once you have the basic t-test under your belt, it might feel natural to compare each group to 0 and conclude that one group is different from 0 and the other one isn’t. But “the difference between significant and not significant is not necessarily itself statistically significant” (Nieuwenhuis, Forstmann, and Wagenmakers 2011). 
:::



How to go from theory to hypotheses to statistical model


## Effect size

With all our talk about estimation above, we didn't say nuch about what precisely was being estimated. 

Effect size: a common language for describing group differences. Pros and cons of this approach. Pro: comparability across studies. Con: loss of information about measures and real-world predictions; dependence on baseline variability. 

Effect sizes (ES):
Cohen’s = m1 - m2 / SD
Units of ES easy to compare across studies
Good for comparison 
Example: school interventions to improve achievement
Necessary for meta-analysis
Example: MA of infant consonant discrimination (cross method comparison)
Necessary for power analysis 
Negative: not related to any real units
Many measures of ES, e.g. r2, n2 (eta), log odds

Precision

Error bar:
 - standard deviation (why is this bad)?
- SEM
- CI

CIs for inference

Confidence intervals:
95% of these regions will contain the TRUE parameter
	Remember frequentists - there is a TRUE parameter

https://istats.shinyapps.io/ExploreCoverage/

But this is not our typical interpretation, which is that 95% chance parameter is in this interval
	That’s the BAYESIAN interpretation

Bayesian Estimation

Find the posterior distribution of the parameter of interest
	You can take its mean
	Its HPD (highest posterior density)

Confidence in confidence intervals: 
https://link.springer.com/article/10.3758/s13423-015-0947-8


::: {.interactive}
⌨️ Interactive box: non-parametric simulations where you can shuffle data across groups a bunch of times and see what kind of distribution it produces by chance
:::

