# Design of experiments {#design}

::: {.learning-goals}
🍎 Learning goals: 

* Describe key elements to designing a manipulation
* Define randomization and counterbalancing strategies for removing confounds
* Discuss strategies to design experiments that are appropriate to the populations of interest
:::

The key thesis of our book is that experiments should be designed to yield precise and unbiased measurements of a causal effect of interest. But the causal effect of what? The manipulation, in a word. In an experiment we intervene on the world and measure the effects of that manipulation. We then compare that measurement to a case where the intervention has not occurred. The previous chapter covered the topic of measurement; here we discuss manipulations.  

We refer to different intervention states as **conditions** of the experiment. The most common experimental design is the comparison between a **control** condition, in which the intervention is not performed, and an **experimental** (or sometimes, **treatment**) condition in which the intervention is performed. But many other experimental designs are possible. The goal of this chapter is to introduce some of these and give you some tools for considering their tradeoffs.  In the first part of the chapter, we'll introduce some common experimental designs and the vocabulary for describing them. 

To be useful, a measure must be a valid measure of a construct of interest. The same is true for a manipulation -- it must validly relate to the causal effect of interest. In the next part of the chapter, we'll discuss issues of **manipulation validity**, including both issues of ecological validity and **confounding**. We'll talk about how practices like **randomization** and **counterbalancing** can help remove nuisance confounds.^[This section will draw on our introduction of causal inference in Chapter \@ref(intro), so if you haven't read that, now's the time.] 

We'll end the chapter by discussing some aspects of strategy in experimental design. How do you design an experiment to test a theory? What sorts of experimental designs are maximally efficient? 

## Experimental designs

Experimental designs are so fundamental to so many fields that they are discussed in many different ways. As a result, the terminology can get quite confusing. Here we'll try to stay consistent by describing an experiment as a relationship between some **manipulation** in which participants are randomly assigned to an experimental condition to evaluate its effects on some **measure**.^[The alternative terminology used in psychology is that of an **independent variable** (the manipulation, which is causally prior and hence "independent" of other causal influences) and a **dependent variable** (the measure, which causally depends on the manipulation, or so we hypothesize). This terminology seems transparently terrible. An alternative is the terms that are often used in econometrics of the **treatment** or **intervention** (manipulation) and the **outcome** (measure). This terminology is clearer, but also has some fairly medical connotations -- it sounds like the treatment is something substantial and lasting, and the outcome is meaningful. That's not always the case in experiments that investigate psychological mechanisms. For example, in a cognitive psychology context, it sounds a bit weird to us to say that the "treatment" was reading scrambled words and the "outcome" was lexical decision reaction times.]

## Factorial experiments

How should we decide what conditions to have in our experiment? The classical "design of experiments" paradigm has as its goal to 

Crossed designs


## Between- vs. within-participant designs

```{r, fig.cap="A between-participants design."}
g <- DiagrammeR::grViz("digraph {
  graph [layout = dot, rankdir = LR]
  
  node [shape = rectangle, style = filled, fillcolor = white]        
  a [label = 'Participant 1']
  b [label = 'Participant 2']
  c [label = 'Participant 3']
  d [label = 'Participant 4']
  
  node [fillcolor = pink]
  c1a [label = 'Experimental Manipulation']
  c1b [label = 'Experimental Manipulation']
  
  node [fillcolor = lightblue]
  c2a [label = 'Control Manipulation']
  c2b [label = 'Control Manipulation']
  
  node [fillcolor = white]
  m1 [label =  'Measure']
  m2 [label =  'Measure']
  m3 [label =  'Measure']
  m4 [label =  'Measure']
  
  # edge definitions with the node IDs
  a -> c1a -> m1
  b -> c1b -> m2
  c -> c2b -> m4
  d -> c2a -> m3
  }")

g$width <- "50%"
g$height <- "100%"
g
```



between
Main advantage
No contamination by other exposure to experimental materials
Disadvantages
Requires many participants
Individual differences create a lot of variability in groups
Potential for assignment bias: need to control for differences between groups
Other environmental group differences


Main advantage
Eliminates subject variability
Relatively few participants needed, because of this lack of variability
Disadvantages
Carryover effects mean that ordering of conditions can be problematic
Not always possible: imagine trying a within-subjects design for surgery
General contention: preferable when possible


## Discrete and continuous experimental manipulations 


Continuous and discrete variables

Dose response relationships 

Multi-experiment design strategy: start simple? 



<!-- ::: {.case-study} -->
<!-- 🔬 Case study: Still suspicious? -->

<!-- The “suspicious coincidence” effect (Xu and Tenenbaum 2007) with non-replication by Spencer et al. (2011) resolved by Lewis & Frank (2018) “still suspicious” paper.  -->
<!-- ::: -->

## Manipulation validity


### Threats to manipulation validity

 - Manipulations must correspond to the construct whose causal effect is being estimated.
 
  - Demand characteristics. How did concerns about demand characteristics emerge? What proposed mechanisms cause demand characteristics to influence participant behavior? What evidence do we have that demand characteristics impact participant behavior? And what strategies can we use to mitigate demand characteristics?

Ecological validity
  
### Confounding


Let's consider an alternate experiment now. Suppose we did the same basic procedure, but now with a "within-subjects" design where participants do both the Dylan treatment and the control, in that order. This experiment is flawed, of course. If you observe a Dylan effect, you can't rule out the idea that participants got tired and wrote worse in the control condition because it always came second.

Order (Dylan first vs. control first; notated X') is an experimental confound: a variable that is created in the course of the experiment that is both causally related to the predictor and potentially also related to the outcome. Here's how the causal model now looks:




We've reconstructed the same kind of confounding relationship we had with age, where we had a variable (X') that was correlated both with our predictor (X) and our outcome (Y)! So...



In the causal language we have been using, counterbalancing allows us to snip out the causal dependency between order and Dylan. Now they are unconfounded (uncorrelated) with one another. We've "solved" a confound in our experimental design. Here's the picture:


These are not covariates! Covariates are related but don't have causal force in this design because of randomization. We can use them in our analysis to make our estimates more precise (see Chapter \@ref(models)), but we won't worry about them here. If someone says to you, "participant gender is a confound in your experiment", if you've done random assignment to condition appropriately (acoss genders), you should say "no it's not."

### Removing nuisance confounds

 What should we do with our experimental confounds? 

Option 1. Randomize. Increasingly, this is my go-to method for dealing with any confound. Is the correct answer on my survey confounded with response side? Randomize what side the response shows up on! Is order confounded with condition? Randomize the order you present in! Randomization is much easier now that we program many of our experiments using software like Qualtrics or code them from scratch in JavaScript.

The only time you really get in trouble with randomization is when you have a large number of options, a small number of participants, or some combination of the two. In this case, you can end up with unbalanced levels of the randomized factors (for example, ten answers on the right side and two on the left). Averaging across many experiments, this lack of balance will come out in the wash. But in a single experiment, it can really mess up your data – especially if your participants notice and start choosing one side more than the other because it's right more often. For that reason, when balance is critical, you want option 2.

Option 2. Counterbalance. If you think a particular confound might have a significant effect on your measure, balancing it across participants and across trials is a very safe choice. That way, you are guaranteed to have no effect of the confound on your average effect. In a simple counterbalance of order for our Dylan experiment, we manipulate condition order between subjects. Some participants hear Dylan first and others hear Dylan second. Although technically we might call order a second "factor" in the experiment, in practice it's really just a nuisance variable, so we don't talk about it as a factor and we often don't analyze it (but see Option 3 below).

Counterbalancing doesn't always work, though. It gets trickier when you have too many levels on a variable (too many Dylan songs!) or multiple confounding variables. For example, if you have lots of different nuisance variables – say, condition order, what writing prompt you use for each order, which Dylan song you play – it may not be possible to do a fully-crossed counterbalance so that all combinations of these factors are seen by equal numbers of participants. In these kinds of cases, you may have to rely on partial counterbalancing schemes or latin squares designs, or you may have to fall back on randomization.

Option 3. Do Options 1 and 2 and then model the variation. This option was never part of my training, but it's an interesting third option that I'm increasingly considering.** That is, we are often faced with the choice between A) a noisy between-participants design and B) a lower-noise within-participants design that nevertheless adds noise back in via some obvious order effect that you have to randomize or counterbalance. In a recent talk by Andrew Gelman, he suggested that we try to model these as covariates, to reduce noise. This seems like a pretty interesting suggestion, especially if the correlation between them and the outcome is substantial.***

## Strategy

### How to design a manipulation to test a theory.

Simplicity as a key design principle

  - E. O. Wilson’s advice: iteration on a repeatable measurement.
  - Statistical and interpretability concerns for complex interaction designs.
  - Nuisance variables: counterbalancing and randomization.

The temptation to manipulate lots of things

Again, we advocate for simplicity.

The advice is out there to


### Connecting with theory


  - The ethics of the “dead on arrival” experiment – why appropriate experimental design is an ethical imperative (we “waste” participant contributions otherwise).
 “risky tests”: those that will best help adjudicate between theories. @meehl1978
  
  Optimal experiment design in psychophysics and beyond – how to use quantitative models to select the stimulus that maximizes your chances of a theory-informing result.





::: {.ethics-box}
🌿 Ethics box: Including the population being sampled in the design process. 
:::

