# Sampling {#sampling}

::: {.learning-goals}
🍎 Learning goals: Learn how to choose an appropriate sample size, generalize notion of sample size to other axes of generalizability (e.g. thinking a process for sampling items in addition to participants), reason about limitations of different samples
:::

::: {.case-study}
🔬 Case study: Majid & Kruspe (2018). Since Darwin, scientists have assumed that smell is a vestigial sense in humans – one that we don’t even bother to encode in language. But in fact this inference may be based on choosing the wrong sample, since multiple hunter-gatherer groups appear to have large vocabularies for consistent smell description. 
:::

The goal of sampling is generalization: but who do we want to generalize to?

  - Ubiquitous convenience sampling
  - The WEIRD framework (and its weaknesses)
  - Representative sampling and stratification for variance reduction
  - Ethical implications of representation in experimental samples

Sample size planning

  - Classic power analysis 
  - Smallest effect size of interest (SESOI analysis)
  - Precision-based sample size planning (Bland 2009; Lash and Kaufman 2015) (malcolmbarrett.shinyapps.io/precisely)
  - Simulation based 
  - Sequential analysis (Schönbrodt et al. 2017)

Where sampling goes wrong:

  - Attrition/survivorship bias (connection to directed acyclic graphs [DAGs] as described earlier)
  - Selection bias (connection to DAGs again)

Participant vs. stimulus sampling

  - What if your effect is generalizable across participants but not across stimuli (Clark 1973).


:::{.exercise}
Form an argument about this controversial position: We want to understand human cognition generally, but it’s a more efficient research strategy to start by studying certain features of cognition (perception, for example) in WEIRD convenience populations and then later check our generalizations in non-WEIRD groups. 
:::

:::{.exercise}
Form an argument about this controversial position: The most influential experiments aren’t generalizations of some number to a population, they are demonstration experiments that show that some particular effect is possible under some circumstances (think Milgram’s conformity studies, where people apparently shocked a confederate at an experimenter’s prompting), so often specific population sampling is secondary.
:::

:::{.exercise}
Form an argument about this controversial position: Nothing you learn from US college undergraduates is likely to generalize to the US population as a whole, so we should dramatically decrease the use of this convenience population. 
:::

:::{.exercise}
Form an argument about this controversial position: We can’t ever make generalizations about the human mind because so much of the historical human population is simply inaccessible to us (we can’t do experiments on ancient Greek psychology). Psychological samples are also sampling a particular moment in time.
:::