# Data collection {#collection}

::: {.learning-goals}
🍎 Learning goals: Reason about the biases that can be introduced by different data collection methods; deploy manipulation checks. 
:::

::: {.case-study}
🔬 Case study: Crump et al. (2013) show through a set of beautiful experiments designed in the web browser how online data collection can replicate effects initially found in the lab. 
:::

Data collection online: Online data collection is increasingly ubiquitous in the behavioral sciences. Further, the web browser – alongside survey software like Qualtrics – can be a major aid to transparency in sharing experimental materials.

- Validating the process of collecting data online. We briefly review studies suggesting that for general data collection across many paradigms, online data collection is valid. 
- When is online not enough? We describe cases where in-person data collection is necessary, highlighting psychophysical and physiological measurement and social interaction as two common classes of experiments that still cannot be done effectively online. 

Data collection in the field: An opinionated discussion of common pitfalls of field experiments in psychology.

- Blinding and randomization. Fieldwork makes it harder to maintain these critical principles of experimental design, potentially leading to bias. 
- Reasoning about and combatting selection bias.

Experimental practices, beliefs, and superstitions

::: {.accident-report}
⚠️ Accident report: ManyLabs 3 (2016) disconfirms the common belief that psychology subject pools vary in quality throughout the semester. 
:::

Documenting your data collection

- Critical value of preserving (and sharing) specifics of data collection.
- Value of raw source video (Gilmore and Adolph 2017)