# Data management {#management}

::: {.learning-goals}
🍎 Learning goals: Recall the risks of data identification, list optimal data management practices, describe important elements of version control, define FAIR data.
:::

::: {.case-study}
🔬 Case study: ManyBabies 1 (2020) conducted a distributed replication of an important effect in developmental psychology. But when they got the data back from all the labs, they were a mess! How do you design a system for making sure that data meet your assumptions?
:::

Anonymization

- What are the risks from data being identifiable to a particular individual?
- Regulatory and ethical frameworks including US DHHS (Department of Health and Human Services) “safe harbor” and European GDPR (General Data Protection Regulation). 

🌿 Ethics box: an awkward email from an MTurk study participant leads to the realization that “anonymous IDs” are not so anonymous after all. More generally, statistical reidentification is easy, even from “anonymized data” (Rocher, Hendrickx, and de Montjoye 2019).

Data management

- Always keep the raw data. 
- Organization and file names. 
- Creating metadata on when/where/who collected data. 

::: {.accident-report}
⚠️ Accidental report: security practices for databases (how not to get hit by a ransomware attack)
:::

Spreadsheet setup: how to organize your data for success (based on Broman and Woo 2018)

- Making data machine-readable (e.g., a clean row-column csv format, not using color-coding or headers to differentiate cells, using consistent coding conventions)
- How to create an informative codebook

Version control – conceptual introduction (Tutorial in Appendix A)

- Version control platforms allow you to save your project, including data, code, etc., as a frozen time capsule along with comments about what was happening at that slice in time. This facilitates jumping back in time to an earlier version and obviates keeping a messy chronological sequence of files locally. 
- Branching: The ability to create another, parallel history for your project, so that you can try out major changes or additions without disturbing the main branch in the process. This facilitates collaboration.
- Transparent committing and pushing, labeled with the user who made the changes, facilitates collaboration.
- Appendix shows how to use git as a version control system.

Data archiving. Making data FAIR: Findable, Accessible, Interoperable, and Reusable (Wilkinson et al. 2016)

- Licensing to prevent legal obstacles for reuse. 
- Selecting an appropriate repository – highlight OSF as fulfilling the FAIR standards, but provide other alternatives (e.g. Dataverse). 
