# (PART) Analysis and reporting {-}

# Visualization {#viz}

::: {.learning-goals}
🍎 Learning goals: Analyze and compare visualizations using principles of visualization; learn to make “the design plot” showing raw data relative to the critical design inferences of the experiment; select different visualizations of variability and distribution; connect these concepts to measurement principles.
:::

::: {.case-study}
🔬 Case study: Sklar et al. (2012) reported evidence of “unconscious” arithmetic. Further reanalyses didn’t support this finding (Moors and Hesselmann 2018). Rabagliati et al. (2018) also failed to replicate. Visualizations provide a framework for asking about the ways the measurements relate to the manipulation that might have shed light on the issues.
:::

Basic principles of visualization. This book will not provide a full treatment of visualizations, but we discuss some basic guidelines. (Tutorial for data manipulation and visualizations in Appendices C and D).

- Statistical visualization vs. infoviz (Gelman and Unwin 2013)
- “Fix the axis labels”
- Principles:
    - Show the design (see below for the “data plot”): make sure that the variables you manipulate are visible in your plots
    - Facilitate comparison: make sure that the contrasts you want to interpret are highlighted visually
    - Maximize information, minimize ink: following Tufte, use the simplest possible presentation of the maximal amount of information.

Exploratory visualization

- The critical importance of visualizing the data distribution (histograms). 
- Mapping “visual variables” (size, color, etc.) to the critical variables in your design


::: {.accident-report}
⚠️ Accident report: [Distributional] gorillas in the midst: Many data analysts don’t bother checking whether they are violating distribution assumptions. If they did, they’d sometimes realize there is a gorilla in the midst (Yanai and Lercher 2020).
:::

Confirmatory visualization (including “The design plot”)

- How to make a plot that maps onto the key, pre-registered analyses
- Different levels of specificity for different audiences 

Visualizing variability

- Measures of precision: confidence intervals and how to extract them from our statistical models.

::: {.interactive}
⌨️ Interactive box: bootstrapping for confidence intervals, a nice generic method for getting some sense of precision. But be careful: there are many common abuses of the bootstrap, for example to obtain inference in small samples.
:::
