# Recruitment and Consent {#consent}

::: {.box .learning-goals}
* Outline the key features of informed consent
* Describe the four components of participant debriefing 
* Identify the additional federal provisions made for vulnerable populations 
:::

In Chapter \@ref(ethics), we introduced the concept of informed consent. By now, you probably understand that ethical concerns are deeply woven into the fibers of rigorous, quality research. When we neglect the impact of our research on the populations we study, we not only violate the documents and governing bodies (like the Belmont Report and the IRB, respectively) that guide the work we do, but we also establish a pattern of imbalance and distrust that hinders our very efforts. Until this point, we have only considered ethics as a theory. If you have been on the edge of your seat waiting for the practical application, you are in luck! 

In this chapter, we are going to put this knowledge into practice by applying what we know about good science to our interactions with human subjects. We will first discuss the components of informed consent, including appropriate language that participants understand, before thinking about what happens at the end of participation. Finally, we will take a look at a few vulnerable populations represented in research, and describe the steps to take that ensure appropriate and equitable participation for all who wish to do so. 

### Informed consent

Let's continue our conversation on informed consent from Chapter \@ref(ethics). Before we can run an experiment with human subjects, we first need to get them to agree to participate. As we mentioned before, this is an important step in data collection, and the both the Office for Human Research Protections (OHRP) and the IRB have clear guidelines about what this process looks like. Ultimately, your drafted consent form will need to be reviewed by your IRB office, and they can advise you on whether you have adequately described all important information for participants to review. Our goal in this section is to get you thinking about good practices for informed consent. Don't wing it; follow the OHRP's "Informed Consent Checklist", which we will summarize below [ohrp1998]. Take a look at this consent form from one of our studies to help you identify lines from the checklist.

<!--consent form and checklist-->

Now that we know what should be included in a consent form, we next need to make sure participants are adequately informed about their upcoming involvement. How can you be reasonably sure of this? 



* comprehension
* voluntary
* competence
* information disclosure
* risks and benefits 

Respect for persons

Informed consent does not mean "giving away" the goal of the study. Demand characteristics 

### Debriefing participants

Every study should have a debriefing to end the study. In general, a debriefing is composed of four parts: (1) participation gratitude, (2) discussion of goals, (3) explanation of deception, and (4) questions and clarification [@allen2017]. 

**Gratitude.** Thank participants for their involvement in research study! Sometimes thanks is enough (for a short experiment), but many studies also include an additional token of appreciation such as monetary compensation or course credit. If monetary or other physical compensation will be implemented, it should be commensurate with the amount of time and effort required for participation. Compensation structures vary widely from place to place; typically local IRBs will have guidelines that they ask researchers to comply with.

**Discussion of goals.** Researchers should briefly share the purpose of the research study with participants. Why were participants recruited for this study in the first place? What are the researchers hoping to learn by conducting this study? It is important to ensure that participants fully understand the goals of the study, so avoiding technical jargon or confusing language is critical. You might also consider sharing any preliminary findings or where to find the completed write-up at the study's conclusion -- many engaged participants really appreciate a link to research findings, even months or years after participation.^[Sharing goals is especially important when some aspect of the study appears evaluative -- participants will often be interested in knowing how well they preformed against their peers. For example, a parent whose child completed a word-recognition task may request information about their child's performance. It is often important to highlight that the goals of the study are not about individual evaluation and ranking.] 

**Explanation of deception.** Researchers must reveal any deception during debriefing, regardless of how minor the deception seems to the researcher. This component of the debriefing process can be thought of as "dehoaxing" because it is meant to illuminate any aspects of the study that were previously misleading or inaccurate [@holmes1976]. The goal is both to reveal the true intent of the study and to alleviate any potential anxiety associated with the deception. After identifying where the deception occurred, it is useful to explain why the deception was necessary for the study's success. 

**Questions and clarification.** Finally, researchers should answer any questions or address any concerns raised by participants. Many researchers use this opportunity to first ask participants about their interpretation of the study, what they thought were the study goals. This not only illuminates aspects of the study design that may have been unclear to or hidden from participants, but it also begins a discussion where both researchers and participants can communicate about this joint experience. This step is also helpful in identifying negative emotions or feelings resulting from the study [@allen2017]. When participants do express negative emotions, researchers are responsible for sharing resources participants can use to work though the discomfort. 

With the widespread use of data collection sites such as Amazon Mechanical Turk (MTurk) and Prolific, many researchers have elected to conduct some or all of their studies online. Debriefing is required regardless of the study's presentation method. When a study is fully automated and participants do not interact with experimenters, researchers can make use of **debriefing statements**. Debriefing statements are documents that summarize all four components of the debriefing process (participation gratitude, discussion of goals, explanation of deception, and questions and clarification). Because experimenters are not present at the end of the study to answer participant questions, the statement typically provides the contact information for both the principal investigator and the IRB office. These communication channels should be clearly conveyed should participants need to follow up about the study for any reason.^[Some studies may not be ethically appropriate for being run online. Studies that have substantial deception or that induce negative emotions may require an experimenter present to alleviate concerns and address points of deception rather than relying on a written statement.]

### Special considerations for vulnerable populations

Regardless of who is participating in research, investigators have an obligation to protect the rights and well-being of all participants. However, some populations should be considered **vulnerable** because of their decreased agency -- either in general or in the face of potentially coercive situations. These populations should receive additional considerations or oversight when involving them in research studies. In this section, we will consider a few common vulnerable populations and discuss whether and how to include them in research studies.

**People with disabilities.** There are thousands of disabilities that affect cognition, development, motor ability, communication, and decision-making with varying degrees of interference, so it is first important to remember that considerations for this population will be just as diverse as its members. Officially, a disability is a diagnosed mental or physical condition that limits or restricts a person's involvement in daily activities [@stineman2001]. Roughly 8% of the US population is disabled, which makes it likely that, in the context of a research study, researchers may come into contact with someone who is disabled. Assuming all general rules and regulations are followed, there are no laws that preclude people with disabilities from participating in research. However, those with cognitive disabilities who are unable to make their own decisions (importantly, this also applies to children with or without disabilities) may only participant with written consent from a legal guardian and with their individual assent (if applicable). This means that even if the person provides assent, researchers may not enroll them in the research study without also obtaining consent from their guardian. Those retaining full cognitive capacity but who have other disabilities that make it challenging to participate normally in the research study should receive appropriate accommodations to access the material, including the study's risks and benefits. 

**Children.** Children are some of the most commonly used vulnerable populations in research because their contributions to our understanding of behavior, development, and cognition [among others] are invaluable. Because they are so invaluable, studying them likely won't go away in your lifetime or mine, so we must be vigilant about how we involve them in studies. Like people with disabilities, children under the age of 18 (though the exact age depends on state and local laws) may only participate in research with written consent from a parent or guardian and sometimes with their individual assent (if applicable). This is because children are not capable of protecting their own well-being, so this responsibility is deferred to the legal caregiver. In addition to the typical protections offered to all human subjects, children are also granted further protections under the law. Most notably, the risks associated with a research study must be no greater than minimal unless participants may receive some direct benefit from participating or participating in the study may improve a disorder or condition of which the participant was formally diagnosed [@ohrp]. This generally means that healthy, or otherwise unaffected, control participants could not be subject to greater than minimal risk. In the event that a caregiver provides written consent but their child of reasonable age and cognitive capacity refuses to provide assent, participation must be abandoned altogether. 

**Prison population.** Nearly 2.1 million people are incarcerated in the United States alone [@gramlich2021]. The use of prisoners in research has been a source of debate for decades, so the Office for Human Research Protections (OHRP) has supported their involvement under limited circumstances [@ohrp2003]. In such circumstances, the IRB has made special provisions to ensure that those with diminished autonomy are protected when participating in research. When researchers propose to study incarcerated individuals, the IRB must reconfigure their board to include at least one active prisoner (or someone who can speak from a prisoner's perspective) and ensure that less than half of the board has any affiliation to the prison system, public or private. After study approval, researchers must follow similar protocols as with other populations we have discussed so far. Importantly, researchers must not suggest or promise that participation will have any bearing on prison sentences or parole eligibility. You can imagine how this incentive would be so great, that it might strongly influence whether a prisoner chooses to participate. Like any other person, prisoners must have the agency to weigh the advantages and disadvantages of their participation, and that any compensation they receive is commensurate with their direct involvement. A question you might ask when determining whether a study involving incarcerated individuals is appropriate is, "Would a reasonable adult participate if they were not imprisoned?"

**Low-income populations.** Low-income populations are exceptional cases because any one person can easily fall under this category in addition to another. Participants with fewer resources may be persuaded by monetary or other economic incentives (think cash payments or gift cards) in exchange for their participation. If you were an attorney, you would call this **undue influence**. In psychology, we call this **social influence**. No matter which you choose, coercing anyone to participate in a study with payment so excessive that it influences their decision to engage should be avoided. When participants are paid fairly for their time and are properly informed about how they will be involved in research, we reduce the risk of exploiting the very populations we seek to support. 

**Crowd workers.** In recent years, researchers have made use of online data collection, or crowdsourcing, to reach a wider population both domestically and internationally. Importantly, crowdsourcing platforms were originally designed for businesses to collect data, not for academic research [@litman2017]. While the IRB has not mandated explicit guidelines for this population at the time this textbook was written, we believe this conversation to be critical as many of you may go on to crowdsource your own data one day. Let's first discuss who are crowd workers. In 2020, nearly 130,000 people completed MTurk studies [@moss2020]. Of those, 70% identified as White, 56% identified as women, and 48% had an annual household income below $50,000. There are several other crowdsourcing websites that we won't share demographics for here, but understanding the general makeup of crowd workers is important for recognizing who we include in our studies. But because crowdsourced research is largely unregulated, it should come as no surprise that exploitation on these platforms exists. A sampling of crowd work determined that the average wage earned was just \$2.00 per hour, and less than 5% of workers were paid at least the federal minimum wage (\$7.25 per hour at the time this textbook was written) [@hara2018]. While some platforms like Prolific have implemented minimum payment standards that all researchers (or requesters on these platforms) must follow, no government agencies have mandated such practices. Requesters also have the option to reject a crowd worker's submission for any reason, meaning that they are paid for their performance rather than their time. Without platform or government standards, it is up to individual requesters to commit to fair pay, which is likely at least the federal minimum wage (if applicable). It may also be easier to commodify crowd workers in ways that would be challenging to do with participants in a lab setting. People who make a career out of evaluating these issues call this commoditization "**human-as-a-service**", or **HaaS** [@xia2022]. Crowd workers alleviated a number of concerns that plagued researchers for decades; with limited budgets and time, reduced person-power, and a push to develop bigger and bigger datasets, HaaS offered relatively simple solutions to these concerns. The only problem? Humans are not commodities, at least not in any reasonable sense. If we, instead, applied IRB guidelines to our interactions with crowd workers, we might conclude that they (1) are research volunteers, not employees or contractors, (2) should be paid for their time, even if their data is ultimately unusable, (3) are entitled to the same level of data protection and anonymity as any other participant, and (4) should be informed about what their participation involves before giving consent. Harnessing the power of online data collection is easy when we treat crowd workers like any other participant protected by the IRB. 

::: {.box .accident_report}
(TITLE) The Tuskegee Syphilis Study 

In 1929, The United States Public Health Service (USPHS) was perplexed by the effects of a particular disease with an epicenter in Macon County, Alabama, with an overwhelmingly Black population [@brandt1978]. Syphilis is a sexually transmitted bacterial infection that can either be in a visible and active stage or in a latent stage. At the time of the study's inception, roughly 36% of Tuskegee's adult population had developed some form of syphilis, one of the highest infection rates in America [@white2006]. 

USPHS recruited 400 Black males from 25--60 years of age with latent syphilis and 200 Black males without the infection to serve as a control group to participate in what would become one of the most exploitative research studies ever done on American soil [@brandt1978]. The USPHS sought the help of the Macon County Board of Health to recruit participants with the promise that they would provide treatment for community members with syphilis. The researchers sought poor, illiterate Blacks and, instead of telling them that they were being recruited for a research study, they merely informed them that they would be treated for "bad blood", a phrase used in that time to refer to syphilis. 

Because the study was only interested in tracking the natural course of latent syphilis without any medical intervention, the USPHS had no intention of providing any care to its participants. To assuage participants, the USPHS distributed an ointment not been shown to be effective in the treatment of syphilis, and only small doses of a medication actually used to treat the infection. In addition, participants underwent a spinal tap which was presented to them as another form of therapy and their "last chance for free treatment." By 1955, just over 30% of the original participants had died from syphilis complications. 

It took until the 1970s before the final report was released and (the lack of) treatment ended. In total, 128 participants died of syphilis or complications from the infection, 40 wives became infected, and 19 children were born with the infection [@katz2011]. The damage rippled through two generations, and many never actually learned what had been done to them. The Tuskeegee experiment violates nearly every single guideline for research described above -- indeed in its many horrifying violations of research participants' agency, it provides a blueprint for future regulation to prevent any aspect of it from being repeated. 

Investigators did not obtain informed consent. Participants were not made aware of all known risks and benefits involved with their participation. Instead, they were deceived by researchers who led them to believe that diagnostic and invasive exams were directly related to their treatment.^[In human subjects research, **deception** is a specific technical term that refers to cases when (1) experimenters withhold any information about its goals or intentions, (2) experimenters hide their true identity (such as when using a confederate), (3) some aspects of the research are under- or overstated to conceal certain information, or (4) participants receive any false or misleading information [@tai2011].]

Participants were denied appropriate treatment following the discovery that penicillin was effective at treating syphilis [@mahoney1943]. The USPHS requested that medical professionals overseeing their care outside of the research study not offer treatment to participants so as to preserve the study's integrity. This intervention violated participants' rights to equal access to care, which should have taken precedence over the results of the study. 

Finally, recruitment was both imbalanced and coercive. Not only were participants selected from the poorest of neighborhoods in the hopes of finding vulnerable populations with little agency, but they were also bribed with empty promises of treatment and a monetary incentive (payment for burial fees, a financial obstacle for many sharecroppers and tenant farmers at the time).
:::

## Chapter summary: Recruitment and Consent

Consent is an ongoing and fluid process that doesn't end once you've gotten a signature. In this chapter, we applied what we learned about human subjects data collection to issues related to informed consent, debriefing, and special considerations for vulnerable populations. Regardless of who you choose to recruit, you'll want to think carefully about how you share the research opportunity with participants. By the time you have finished explaining what their involvement will look like, participants should understand what is being asked of them, have the cognitive capacity to give consent (or have someone who can), and provide this consent voluntarily. 

