# Exploratory data analysis {#eda}

::: {.learning-goals}
🍎 Learning goals: Explain how to evaluate the sensitivity of main analyses to modeling assumptions, describe how modeling and data visualization support data analysis, compare individual and item differences. 
:::

::: {.case-study}
🔬 Case study: Frank, Vul, & Johnson (2009) report a small subset of the many many analyses they ran on a very rich dataset. Luckily, the simplest analysis was the most important, and that one was replicable (Frank, Amso, and Johnson 2014).
:::

Exploring the sensitivity of your main analyses: covariates and exclusions

- Sensitivity analysis for parameters

::: {.interactive}
⌨️ Interactive box: multi-verse analysis (effects of alternative choices)
:::

Exploratory modeling and model+data visualization: a continuous loop

- How to constrain and document exploratory analysis
- Devil and the deep blue sea post (Danielle Navarro)

Fancy stuff and when it is and isn’t appropriate

- Dimensionality reduction: factor analysis and PCA (when these techniques are useful, and roughly what they do; no mathematical exploration). 
- Using cognitive models as predictors: an exciting way of making quantitative links between theory and data.
- Exploiting variation: individual differences and item differences. (Some discussion of psychometric models like item response theory as a way of exploring this variation). 
