<!-- # (PART) Reporting and contextualizing {-} -->

# Reproducible writing {#writing}

::: {.learning-goals}
🍎 Learning goals: Justify reproducible writing practices; select an appropriate platform for reproducible writing; explore writing techniques to signal exploratory/confirmatory distinctions
:::

::: {.case-study}
🔬 Case study: Reinhart & Rogoff (2010) had a typo in their excel formula, contributing to widespread adoption of fiscal austerity policies. More broadly, there are likely cut and paste typos in half of published research (Nuijten et al. 2016)!
:::

Why write a reproducible manuscript?

- Minimize human error
- Makes provenance tracking easier (reconstructing how specific figures/tables were generated) 
- Makes formatting changes easier (e.g., MLA to APA; different journal formats) 
- Enables other researchers to run the same analyses with new data

Writing a reproducible manuscript allows researchers to generate results and figures via direct computation rather than having to manually copy them into the manuscript. 

- Literate programming (Knuth 1992): Instead of supporting code with documentation (e.g., code), reverse the emphasis by supporting documentation (e.g., your manuscript) with code (e.g., using R Markdown)

::: {.accident-report}
⚠️ Accident report: Frank et al. (2009) correction due to bad coding practices.
:::

- Reproducible data analysis: anyone else should be able to run your script and obtain identical results
    - Defensive coding: assume errors are inevitable, include assert statements and sanity checks, catch incorrect inputs (Stodden et al. 2016)
    - Use free/open-source software when possible
    - Use version control (see Chapter 12 for conceptual overview, Appendix B for tutorial)
- Preserving the computational environment (e.g., Code Ocean), preserve package versions (e.g., renv for R, pip freeze for Python)

Dealing with errors

::: {.accident-report}
⚠️ Accident report: Julia Strand discovered a coding error in a key paper for her career at exactly the wrong time, but she took the plunge and corrected it (Julia Feld Strand 2020; Julia F. Strand, Brown, and Barbour 2019).
:::

🔬 Case study: The Red Team Challenge: Why I placed a bounty on my own research.
:::

  - The correction and retraction processes

How (not) to write the empirical paper

::: {.accident-report}
⚠️ Accident report: Daryl Bem’s infamous HARKING chapter encouraged people to tell a post-hoc story about data, but this practice is very problematic (Bem 1987)
:::

::: {.ethics-box}
🌿 Ethics box: Sex, gender, and binaries. How our analytic and reporting decisions can reify binaries that we might not believe or intend. One possible case study: one very useful study (Stoet and Geary 2013) of sex differences in math and reading nevertheless conflates sex and gender. 
:::

What does it mean? 

- How do data constrain theories? Connecting back to pieces on theory development in earlier chapters. 
- The iterative relationship between experimentation and theory building.
- Bayesian model selection as a tool for comparing theories
