<!-- # (PART) Reporting and contextualizing {-} -->

# Writing {#writing}

::: {.learning-goals}
🍎 Learning goals: Justify reproducible writing practices; select an appropriate platform for reproducible writing; explore writing techniques to signal exploratory/confirmatory distinctions
:::

::: {.case-study}
🔬 Case study: Reinhart & Rogoff (2010) had a typo in their excel formula, contributing to widespread adoption of fiscal austerity policies. More broadly, there are likely cut and paste typos in half of published research (Nuijten et al. 2016)!
:::

## Writing clearly

What is the purpose of writing? “Telepathy, of course.” - Stephen King (2000) On Writing. We need to transfer information to the reader in the most efficient and clear way possible. How can we do this? There are no hard and fast rules of good writing. Here we will share a few of our own ideas and highlight some key conventions of scientific writing.

Maximise the signal to noise ratio: remove irrelevant clutter and distractions [@doumont2009].

Just as we want computer software to be user-friendly, we want our written documents to be reader-friendly.

There are no strict rules of good writing, but there are conventions (as expected by academic journals) and advice (which we can offer from our experience). Writing is an art form - though scientific writing usually has to follow certain conventions, it doesn't necessarily have to be dry. There are ways to surprise and excite your reader with the use of metaphor or even humour. There's enjoyment to be found in expressing complex topics in a an elegant fashion.

We also recommend @doumont2009, a paen to rational communication structures. 

Academic standards: IMRaD and hourglass structure. Standard APA format and the "random access" document (folks don't necessarily read papers linearly or in their entirety)

Articles have a hierarchical structure - sections, paragraphs, sentences, words.

Paragraphs and topic sentences. Start and end paragraphs like a relay race where the baton is passed between paragraphs.

Be concise. "Omit needless words." - William Strunk. For example, *in the event that* vs. *if*. Or *we performed an investigation of* vs. *we investigated*. Your first draft will rarely be as concise as possible. Each time you read through, omit needless words.

Use active voice rather than passive voice. For example, say "We analyzed the data" rather than "The data were analysed" or, worse, "An analysis of the data was carried out". The first passive voice example is ambiguous (who were the data analysed by?) and the second is ambiguous and long-winded. The active voice is clear about the agent (the authors analyzed the data) and is concise. Historically, scientific articles tended to be written passive voice because it (allegedly) conveyed a aura of objectivity. However, this is illusory, and active voice is usually clearer and more concise. Another example: "It is believed that..." vs. "We believe that..." or "Scientists believe that..."

Consider the audience you are writing for and calibrate your writing accordingly

Always think about the reader while you write. You cannot assume they have the same knowledge as you, you need to guide them.

Define technical terminology then use it consistently - for example, replication and reproducibility may sound similar, but they have important technical definitions, so do not use them interchangeably. And be clear about the definition you are going to be using.

Use abbreviations sparing - they create unnecessary cognitive load if the reader has to keep track of lots of them (an exception might be definitions that are very common in your field e.g., fMRI, but you should at least define them and always consider your audience - if you think your work may appeal to readers who do not know the abbreviation then avoid using it)

Scientific writing does not have to be dull and boring - the best scientist writers find a way to create a style that is both professional and elegant - sometimes even funny!

Ensure that when you make empirical claims you back them up with evidence.

Your goal is not to convey everything you know about a topic, but rather to clearly communicate a limited set of specific messages. Decide what those messages are and focus only on them. For example, in the introduction

Use examples - sometimes your attempts to convey concepts to the reader may fail and leave them adrift, a concrete example gives the reader something to hold on to.

Use figures and diagrams - for example, to describe a series of particant exclusions, use a flow diagram. If the journal limits the number of figures you can use, make use of the supplementary materials.

It may be useful to add sub-sections to, for example sections of the results that refer back to each hypothesis. Number sections. 

Use cross-referencing - identify hypotheses with letters (A, B, C) etc or numbers; refer to sections; refer to supplementary materials; refer to tables, figures, etc.

A paragraph is a meaningful chunk of information. 

Paragraph structure - PEEL - Point Explain Evidence Link. Make your point, explain further / expand on your point, provide evidence, link back to your orginal point and to the next paragraph. 

One idea to try - build up your article layer by layer - start with the sections, then add the signpost sentences of each paragraph, then add the sentences in those paragraphs.

Research articles have some special sections that may break from the typical paragraphing structure - for example, the abstract is one big paragraph that consists of several messages (perhaps better to think of the abstract as several mini paragraphs chained together) and the procedure section may be better as numeric bullet points (to indicate the sequential order in which methodological tasks were performed).

We hope these tips are useful, but also note that it can be hard to learn good writing by trying to learn and follow a set of explicit instructions. A more natural way to improve your writing is to read examples of good writing. Just as you learned to talk about imitating the speech of your parents and teachers

How to find these? When a piece of writing strikes you as particularly clear, read more work by the same person. Practice writing regularly yourself. Additionally, try to get honest feedback on your writing from friends or colleagues. Most of us pick up bad habits; improving your writing is an ongoing process - you do not need to learn to write well before writing - just dive in! Over time, you will improve, but its likely you'll pick up bad habits as well as good ones (we sure have), and you'll need your colleagues feedback to weed those out.

[historical side note - clarity of communication was one of the foundational principles of modern science.  Alchemists had a habit of deliberately obscuring their work - sometimes even writing in cryptic codes. Francis Bacon and Robert Boyle pushed for transparency and clarity. Notoriously, Issac Newton (an alchemist turned scientist), continued to deliberately write in an obscure fashion in order to 'protect' his work. See Stephen Heard book chapter 1.]

## Writing reproducibly

Why write a reproducible manuscript?

- Minimize human error
- Makes provenance tracking easier (reconstructing how specific figures/tables were generated) 
- Makes formatting changes easier (e.g., MLA to APA; different journal formats) 
- Enables other researchers to run the same analyses with new data

Writing a reproducible manuscript allows researchers to generate results and figures via direct computation rather than having to manually copy them into the manuscript. 

- Literate programming (Knuth 1992): Instead of supporting code with documentation (e.g., code), reverse the emphasis by supporting documentation (e.g., your manuscript) with code (e.g., using R Markdown)

- Reproducible data analysis: anyone else should be able to run your script and obtain identical results
    - Defensive coding: assume errors are inevitable, include assert statements and sanity checks, catch incorrect inputs (Stodden et al. 2016)
    - Use free/open-source software when possible
    - Use version control (see Chapter 12 for conceptual overview, Appendix B for tutorial)
- Preserving the computational environment (e.g., Code Ocean), preserve package versions (e.g., renv for R, pip freeze for Python)





::: {.ethics-box}
🌿 Ethics box: Sex, gender, and binaries. How our analytic and reporting decisions can reify binaries that we might not believe or intend. One possible case study: one very useful study (Stoet and Geary 2013) of sex differences in math and reading nevertheless conflates sex and gender. 
:::

What does it mean? 

- How do data constrain theories? Connecting back to pieces on theory development in earlier chapters. 
- The iterative relationship between experimentation and theory building.
- Bayesian model selection as a tool for comparing theories


## Writing responsibly


How (not) to write the empirical paper

::: {.accident-report}
⚠️ Accident report: Daryl Bem’s infamous HARKING chapter encouraged people to tell a post-hoc story about data, but this practice is very problematic (Bem 1987)
:::

- separating exploratory and confirmatory

- The correction and retraction processes

- preregistration and deviation

- discussing limitations

- reporting guidelines (maybe)

### Authorship
<p> Why it matters/saving yourself the trouble </p>
<p> When to have the conversation </p>
<p> When to re-evaluate </p>

### Disclosures
<p> Why it matters </p>
<p> Financial statements </p>
<p> Conflicts of interest </p>

### Generalizability Statements
<p> Purpose and why it matters </p>
<p> Important elements </p>
<p> Example statement </p>

## Post-publication

Errors

<p> Don't ignore it! </p>
<p> How to remedy it </p>
<p> Why it matters </p>


Dealing with errors

::: {.accident-report}
⚠️ Accident report: Julia Strand discovered a coding error in a key paper for her career at exactly the wrong time, but she took the plunge and corrected it (Julia Feld Strand 2020; Julia F. Strand, Brown, and Barbour 2019).
:::

A note on collaboration? (e.g., google docs, giving feedback on writing?)

