# Conclusions {#conclusions}

<!-- * Present a checklist for researchers -->

::: {.box .learning_goals}
* Synthesize the viewpoint of this book
* Discuss the outlook for psychology in light of the open science movement
:::

You've made it to the end of Experimentology, our (sometimes opinionated) guide to how to run psychology experiments. This final chapter will briefly summarize a few of the lessons we think are most important, both for researchers and for the field of psychology more broadly. 

## Lessons for individual researchers

Experimentology is a big book, and incorporating all of our advice into your research program may seeem daunting! 


- Start simple, and repeat: for building an empirical research program, you want to measure one thing well and then build on that measurement. 
- Internal replication as a critical way to check your own work. 
- Cumulativity as a key principle that you can model in your own work. 

<!-- ## Section-by-section checklists for experiments -->





## Lessons for the field of psychology

Revisiting themes of precision, transparency, generalizability, bias-reduction

- Discuss the “crisis” narrative and reframe as one way into seeing the set of interlocking issues that keep behavioral research from contributing to cumulative theory.
- Collaboration as a way forward. Spotlight the Psychological Science Accelerator (Moshontz et al. 2018).


## Chapter summary: Conclusion

If there's one thing we can leave you with, it is that doing experiments is a  craft, one that requires practice and attention. The first experiment you run will have limitations and issues. So will the 100th. But as you refine your skills, the quality of the studies you design will get better. Further, your own ability to judge others' experiments will improve as well, making you a more discerning consumer of empirical results. We hope we've provided you with a guide to some of the ways that experiments can go wrong (and go right), but in the end there is no mechanistic solution to the problem of doing experiments with humans. There is only the process of thinking through your design choices -- and considering their consequences for your conclusions. 