project:
  title: "Experimentology for Undergrads"
  output-dir: _site-undergrad

format:
  html:
    theme:
      light: [flatly, resources/scss/global.scss]
      dark: [darkly, resources/scss/global.scss]
    published-title: "Updated"

book:
  title: "Experimentology"
  subtitle: "An Open Science Approach to Experimental Psychology Methods for Undergraduates"
  author:
    - Michael C. Frank
    - Mika Braginsky
    - Julie Cachia
    - Nicholas Coles
    - Tom E. Hardwicke
    - Robert Hawkins
    - Maya Mathur
    - Rondeline Williams
    - Adapted for undergraduates by Russ Poldrack
  date: last-modified
  repo-url: https://github.com/langcog/experimentology
  repo-actions: [source, issue]
  downloads: [pdf]
  back-to-top-navigation: true
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - 001-experiments.qmd
        - 002-theories.qmd
        - 003-replication.qmd
        - 004-ethics.qmd
    - part: "Statistics"
      chapters:
        - 005-estimation.qmd
        - 006-inference.qmd
        - 007-models.qmd
    - part: "Planning"
      chapters:
        - 008-measurement.qmd
        - 009-design.qmd
        - 010-sampling.qmd
    - part: "Execution"
      chapters:
        - 011-prereg.qmd
        - 012-collection.qmd
        - 013-management.qmd
    - part: "Reporting"
      chapters:
        - 014-writing.qmd
        - 015-viz.qmd
        - 016-meta.qmd
        - 017-conclusions.qmd
  # appendices:
  #   - 100-instructors.qmd
  #   # - 100-appendices.qmd # only for latex output
  #   - 101-github.qmd     # only for html output
  #   - 102-rmarkdown.qmd  # only for html output
  #   - 103-tidyverse.qmd  # only for html output
  #   - 104-ggplot.qmd     # only for html output
