project:
  type: book
  preview:
    port: 4200
  post-render:
    - scripts/fix_parts.sh
    - scripts/rerender.R

resources:
  - CNAME
  
reference-location: margin # footnotes in margin
link-citations: true       # citations link to references

bibliography: experimentology.bib
reference-section-title: ""

crossref:
  fig-prefix: figure
  tbl-prefix: table
  sec-prefix: section

language:
  crossref-ch-prefix: chapter
  crossref-apx-prefix: appendix

df-print: kable
filters:
  - boxes

pdf-engine: lualatex

format:
  html:
    theme:
      light: [flatly, resources/scss/global.scss]
      dark: [darkly, resources/scss/global.scss]
    published-title: "Updated"

  pdf:
    documentclass: scrreprt
    classoption: [numbers=noenddot,DIV=11,twoside,open=right]
    keep-tex: true
    include-in-header: resources/tex/preamble.tex
    include-after-body: resources/tex/postamble.tex
    template-partials:
      - resources/tex/partials/before-body.tex
    citeproc: false # don't run pandoc default citation handling
    csl: chicago-author-date-custom.csl
    filters:
      - section-bibliographies
      - fix-latex
    toc-depth: 1 # level 1 headings (i.e. parts and chapters)
    toc-title: Contents # title of table of contents
    links-as-notes: true # turn URLs into sidenotes
    citecolor: DarkGreen # tufte color
    urlcolor: DarkGreen # tufte color
    linkcolor: DarkBlue # tufte color
    filecolor: DarkBlue # tufte color
    # lot: true

knitr:
  opts_chunk:
    comment: "#>"
    collapse: TRUE
    cache.lazy: FALSE
    dev: "png"
    dpi: 300

execute: 
  echo: false
  message: false
  warning: false
  error: false
  cache: true
  code-overflow: wrap
  tidy: true

book:
  title: "Experimentology"
  subtitle: "An Open Science Approach to Experimental Psychology Methods"
  author:
    - name: Michael C. Frank
      orcid: 0000-0002-7551-4378
    - name: Mika Braginsky
      orcid: 0000-0001-9039-3220
    - name: Julie Cachia
      orcid: 0000-0001-9584-457X
    - name: Nicholas A. Coles
      orcid: 0000-0001-8583-5610
    - name: Tom E. Hardwicke
      orcid: 0000-0001-9485-4952
    - name: Robert D. Hawkins
      orcid: 0000-0003-0434-8736
    - name: Maya B. Mathur
      orcid: 0000-0001-6698-2607
    - name: Rondeline Williams
      orcid: 0000-0002-2690-1603
  date: last-modified
  # doi: 10.25936/3jp6-5m50
  repo-url: https://github.com/langcog/experimentology
  repo-actions: [source, issue]
  downloads: [pdf]
  sidebar:
    style: "docked"
    footer: license.qmd
  google-analytics: G-659MTW4XZ4
  # cookie-consent: true
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - 001-experiments.qmd
        - 002-theories.qmd
        - 003-replication.qmd
        - 004-ethics.qmd
    - part: "Statistics"
      chapters:
        - 005-estimation.qmd
        - 006-inference.qmd
        - 007-models.qmd
    - part: "Planning"
      chapters:
        - 008-measurement.qmd
        - 009-design.qmd
        - 010-sampling.qmd
    - part: "Execution"
      chapters:
        - 011-prereg.qmd
        - 012-collection.qmd
        - 013-management.qmd
    - part: "Reporting"
      chapters:
        - 014-writing.qmd
        - 015-viz.qmd
        - 016-meta.qmd
    - 017-conclusion.qmd
