project:
  type: book
  preview:
    port: 4200

metadata-files:
  - _book.yml
  
# cap-location: margin       # figure and table captions in margin
reference-location: margin # footnotes in margin
link-citations: true       # citations link to references

bibliography: experimentology.bib
reference-section-title: References

df-print: kable
filters:
  - boxes
  - section-bibliographies

format:
  html:
    theme:
      light: [flatly, resources/scss/global.scss]
      dark: [darkly, resources/scss/global.scss]
    published-title: "Updated"

  pdf:
    documentclass: scrreprt
    keep-tex: true
    include-in-header: resources/tex/preamble.tex
    citeproc: false # don't run pandoc default citation handling
    toc-depth: 1 # level 1 headings (i.e. parts and chapters)
    toc-title: Contents # title of table of contents
    # links-as-notes: true # turn URLs into sidenotes
    lot: true
    mainfont: ETbb # tufte font
    sansfont: Source Sans Pro
    citecolor: DarkGreen # tufte color
    linkcolor: DarkBlue # tufte color
    urlcolor: DarkGreen # tufte color

knitr:
  opts_chunk:
    comment: "#>"
    collapse: TRUE
    cache.lazy: FALSE
    dev: "png"
    dpi: 300

execute: 
  echo: false
  message: false
  warning: false
  error: false
  cache: true
  code-overflow: wrap
  tidy: true
