::: {.content-visible when-format="html"}
::: {.quarto-title-citeas .csl-entry}
Frank, M. C., Braginsky, M., Cachia, J., Coles, N. A., Hardwicke, T. E., Hawkins, R. D., Mathur, M. B., & Williams, R. 2025. _Experimentology: An Open Science Approach to Experimental Psychology Methods_. Stanford University. <a href="https://doi.org/10.25936/3JP6-5M50">https://doi.org/10.25936/3JP6-5M50</a>. (Also published by MIT Press, ISBN 978-0-262-55256-1)
:::
:::

# Preface {.unnumbered #sec-preface}

As scientists and practitioners, we often want to create generalizable, causal theories of human behavior. As it turns out, experiments---in which we use random assignment to measure a causal effect---are an unreasonably effective tool to help with this task. But how should we go about doing good experiments?

This book provides an introduction to the workflow of the experimental researcher working in psychology or the behavioral sciences more broadly. The organization of the book is sequential, from the planning stages of the research process through design, data gathering, analysis, and reporting. We introduce these concepts via narrative examples from a range of subdisciplines, including cognitive, developmental, and social psychology. Throughout, we also illustrate the pitfalls that led to the "replication crisis" in psychology. 

To help researchers avoid these pitfalls, we advocate for an open science--based approach in which transparency is integral to the entire experimental workflow. We provide readers with guidance for preregistration, project management, data sharing, and reproducible report writing. 

## The story of this book {-}

Experimental Methods (Psych 251) is the foundational course for incoming graduate students in the Stanford psychology department. The course goal is to orient students to the nuts and bolts of doing behavioral experiments, including how to plan and design a solid experiment and how to avoid common pitfalls regarding design, measurement, and sampling. 

Almost all student coursework both before and in graduate school deals with the content of their research, including theories and results in their areas of focus. In contrast, our course is sometimes the only one that deals with the *process* of research, from big questions about why we do experiments and what it means to make a causal inference all the way to the tiny details of project organization, such as what to name your directories and how to make sure you don't lose your data in a computer crash. 

This observation leads to our book's title. "Experimentology" is the set of practices, findings, and approaches that enable the construction of robust, precise, and generalizable experiments. 

The centerpiece of the Experimental Methods course is a replication project, reflecting a teaching model first described in [@frank2012]{.content-visible when-format="html"} [Frank and Saxe (\citeproc{ref-frank2012}{2012})]{.content-visible when-format="pdf"} and later expanded on in [@hawkins2018]{.content-visible when-format="html"} [Hawkins et al. (\citeproc{ref-hawkins2018}{2018})]{.content-visible when-format="pdf"}. Each student chooses a published experiment in the literature and collects new data on a preregistered version of the same experimental paradigm, comparing their result to the original publication. Over the course of the quarter, we walk through how to set up a replication experiment, how to preregister confirmatory analyses, and how to write a reproducible report on the findings. The project teaches concepts like reliability and validity, which allow students to analyze choices that the original experimenters made---often choices that could have been made differently in hindsight!

At the end of the course, we reap the harvest of these projects. The project presentations are a wonderful demonstration of both how much the students can accomplish in a quarter and how tricky it can be to reproduce (redo calculations in the original data) and replicate (recover similar results in new data) the published literature. Often our replication success rate for the course hovers just above 50%, an outcome that can be disturbing or distressing for students who assume that the published literature reports the absolute truth.

This book is an attempt to distill some of the lessons of the course (and students' course projects) into a textbook. We'll tell the story of the major shifts in psychology that have come about in the last ten years, including both the "replication crisis" and the positive methodological reforms that have resulted from it. Using this story as motivation, we will highlight the importance of transparency during all aspects of the experimental process from planning to dissemination of materials, data, and code. 

## What this book is and isn't about {-}

This book is about psychology experiments. These will typically be short studies conducted online or in a single visit to a lab, often---though certainly not always---with a convenience sample. When we say "experiments" here, we mean **randomized experiments** where some aspect of the participants' experience is **manipulated** by the experimenter and then some outcome variable is **measured**.^[We use **bold** to indicate the introduction of new technical terms.]

The central thesis of the book is that:

> Experiments are intended to make maximally unbiased, generalizable, and precise estimates of specific causal effects. 

\noindent We'll explore the implications of this thesis for a host of topics, including causal inference, experimental design, measurement, sampling, preregistration, data analysis, and many others. 

Because our focus is on experiments, we won't be talking much about observational designs, survey methods, or qualitative research; these are important tools and are appropriate for a whole host of questions, but they aren't our focus here. We also won't go into depth about the many fascinating methodological and statistical issues brought up by single-participant case studies, longitudinal research, field studies, or other methodological variants. Many of the concerns we raise are still important for these types of studies, but some of our advice won't transfer to these less common designs.

Even for students who are working on nonexperimental research, we expect that a substantial part of the book content will still be useful, including chapters on replication (@sec-replication), ethics (@sec-ethics), statistics (chapters [-@sec-estimation], [-@sec-inference], [-@sec-models]), sampling (@sec-sampling), project management (@sec-management), and reporting (chapters [-@sec-writing], [-@sec-viz], [-@sec-meta]).

In our writing, we presuppose that readers have some background in psychology, at least at an introductory level. In addition, although we introduce a number of statistical topics, readers might find these sections more accessible with an undergraduate statistics course under their belt. Finally, our examples are written in the R statistical programming language, and for chapters on statistics and visualization especially (chapters [-@sec-estimation], [-@sec-inference], [-@sec-models], [-@sec-viz], [-@sec-meta]), some familiarity with R will be helpful for understanding the code. None of these prerequisites are necessary to read the book, but we offer them so that readers can calibrate their expectations.

## How to use this book {-}

The book is organized into five main parts, mirroring the timeline of an experiment: (1) "Foundations," (2) "Statistics," (3) "Planning," (4) "Execution," and (5) "Reporting." We hope that this organization makes it well suited for teaching or for use as a reference book.^[If you are an instructor who is planning to adopt the book for a course, you might be interested in our resources for instructors, including sample course schedules, in @sec-instructors.]

The book is designed for a course for graduate students or advanced undergraduates, but the material is also suitable for self-study by anyone interested in experimental methods, whether in academic psychology or any other context---in or out of academia---in which behavioral experimentation is relevant. We also hope that some readers will come to particular chapters of the book because of an interest in specific topics like measurement (@sec-measurement) or sampling (@sec-sampling) and will be able to use those chapters as stand-alone references. And finally, for those interested in the "replication crisis" and subsequent reforms, chapters [-@sec-replication], [-@sec-prereg], and [-@sec-management] will be especially interesting. 

Ultimately, we want to give you what you need to plan and execute your own study! Instead of enumerating different approaches, we try to provide a single coherent---and often quite opinionated---perspective, using marginal notes and references to give pointers to more advanced materials or alternative approaches. Throughout, we offer: 

* [**case studies**]{.smallcaps} that illustrate the central concepts of a chapter
* [**accident reports**]{.smallcaps} describing examples where poor research practices led to issues in the literature
* [**depth boxes**]{.smallcaps} providing simulations, linkages to advanced techniques, or more nuanced discussion

While case studies are often integral to the chapters, the other boxes can typically be skipped without issue. 

## Themes {-}

We highlight four major cross-cutting themes for the book: [transparency]{.smallcaps}, [measurement precision]{.smallcaps}, [bias reduction]{.smallcaps}, and [generalizability]{.smallcaps}.^[Themes are noted using [small caps]{.smallcaps}.]

* [transparency]{.smallcaps}: For experiments to be reproducible, other researchers need to be able to determine exactly what you did. Thus, every stage of the research process should be guided by a primary concern for transparency. For example, preregistration creates transparency into the researcher's evolving expectations and thought processes; releasing open materials and analysis scripts creates transparency into the details of the procedure. 
* [measurement precision]{.smallcaps}: We want researchers to start planning an experiment by thinking: "What causal effect do I want to measure?" and to make planning, sampling, design, and analytic choices that maximize the precision of this measurement. A downstream consequence of this mindset is that we move away from a focus on dichotomized inferences about statistical significance and toward analytic and meta-analytic models that focus on continuous effect sizes and confidence intervals.
* [bias reduction]{.smallcaps}: While precision refers to random error in a measurement, measurements also have systematic sources of error that bias them away from the true quantity. In our samples, analyses, and experimental designs, and in the literature, we need to think carefully about sources of bias in the quantity being estimated. 
* [generalizability]{.smallcaps}: Complex behaviors are rarely universal across all settings and populations, and any given experiment can only hope to cover a small slice of the possible conditions where a behavior of interest takes place. Psychologists must therefore consider the generalizability of their findings at every stage of the process, from stimulus selection and sampling procedures to analytic methods and reporting.

Throughout the book, we will return to these four themes again and again as we discuss how the decisions made by the experimenter at every stage of design, data gathering, and analysis bear on the inferences that can be made about the results. The introduction of each chapter highlights connections to specific themes. 

## The software toolkit for this book {-}

We introduce and advocate for an approach to reproducible study planning, analysis, and writing. This approach depends on an ecosystem of open-source software tools, which we introduce in the book's appendices:^[These appendices are available online at <https://experimentology.io> but not in the print version of the book, since their content is best viewed in the web format.]

* the R statistical programming language and the [RStudio](https://posit.co/download/rstudio-desktop) integrated development environment
* version control using Git\index{Git} and [GitHub](https://github.com) for allowing collaboration on text documents like code, prose, and data, storing and integrating contributions over time (@sec-git)
* the `RMarkdown` and `Quarto` tools for creating reproducible reports that can be rendered to a variety of formats (@sec-rmarkdown)
* the `tidyverse` family of R packages, which extend the basic functionality of R with simple tools for data wrangling, analysis, and visualization (@sec-tidyverse)
* the `ggplot2` plotting package, which makes it easy to create flexible data visualizations for both confirmatory and exploratory data analyses  (@sec-ggplot)

Where appropriate, we provide **code boxes** that show the specific `R` code used to create our examples. 

## Onward! {-}

Thanks for joining us for *Experimentology*! Whether you are casually browsing, doing readings for a course, or using the book as a reference in your own experimental work, we hope you find it useful. Throughout, we have tried to practice what we preach in terms of reproducibility, and so the full source code for the book is available at <https://github.com/langcog/experimentology>. We encourage you to browse, comment, and log issues or suggestions.^[The best way to give us specific feedback is to create an issue on our github page at <https://github.com/langcog/experimentology/issues>.]

<!-- ## Integrating this book into an experimental methods course {-} -->

<!-- The project-based approach (argument for doing replication/reproducibility study as part of learning methods)  -->
<!-- Each chapter ends with a mixture of discussion questions, exercises, and project milestones that can be integrated into course assignments.  -->
<!-- We include links to appendices, references, and recurring boxes with ethical content and ‘accident reports’ from documented problems in the literature.  -->

::: {.content-visible when-format="html"}

## Citing this book

::: {#quarto-appendix .default}
BibTeX citation:
<pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@book{experimentology2025,
  author    = {Frank, Michael C. and Braginsky, Mika and Cachia, Julie and Coles, Nicholas A. and Hardwicke, Tom E. and Hawkins, Robert D. and Mathur, Maya B. and Williams, Rondeline},
  title     = {{Experimentology: An Open Science Approach to Experimental Psychology Methods}},
  year      = {2025},
  publisher = {Stanford University},
  doi       = {10.25936/3JP6-5M50},
  note      = {Also published by MIT Press, ISBN 978-0-262-55256-1}
}</code></pre>

For attribution, please cite this work as:
<div id="ref-experimentology2025" class="csl-entry quarto-appendix-citeas">
Frank, M. C., Braginsky, M., Cachia, J., Coles, N. A., Hardwicke, T. E., Hawkins, R. D., Mathur, M. B., & Williams, R. 2025. _Experimentology: An Open Science Approach to Experimental Psychology Methods_. Stanford University. <a href="https://doi.org/10.25936/3JP6-5M50">https://doi.org/10.25936/3JP6-5M50</a>. (Also published by MIT Press, ISBN 978-0-262-55256-1)
</div>
:::

:::

## Acknowledgments

Thanks first and foremost to the many generations of students and TAs in Stanford Psych 251, who have collectively influenced the content of this book through their questions and interests. 

Thanks to the staff at the MIT Press, especially Philip Laughlin and Amy Brand, for embracing a vision of a completely open web textbook that is also reviewed and published through a traditional press. We appreciate your support and flexibility. 

We adapt the Contributor Roles (CRediT) Taxonomy^[Learn more at <https://credit.niso.org>.] to describe our contributions to this manuscript, and we recommend that you do so in your work as well. 

- [Preface](#sec-preface)
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}: {{< var authors.tom >}}
- [Chapter @sec-experiments]
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.c >}}: {{< var authors.nicholas >}}
  - {{< var roles.e >}}: {{< var authors.tom >}}
- [Chapter @sec-theories]
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}s: {{< var authors.nicholas >}} and {{< var authors.tom >}}
- [Chapter @sec-replication]
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}s: {{< var authors.maya >}}, {{< var authors.tom >}}, and {{< var authors.nicholas >}}
- [Chapter @sec-ethics]
  - {{< var roles.w >}}: {{< var authors.rondeline >}}
  - {{< var roles.c >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}s: {{< var authors.tom >}} and {{< var authors.julie >}}
- [Chapter @sec-estimation]
  - {{< var roles.c >}}s: {{< var authors.maya >}}, {{< var authors.nicholas >}}, and {{< var authors.mike >}}
  - {{< var roles.e >}}s: {{< var authors.julie >}} and {{< var authors.tom >}}
- [Chapter @sec-inference]
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.c >}}: {{< var authors.maya >}}
  - {{< var roles.e >}}s: {{< var authors.julie >}} and {{< var authors.tom >}}
- [Chapter @sec-models]
  - {{< var roles.c >}}s: {{< var authors.maya >}} and {{< var authors.mike >}}
  - {{< var roles.e >}}s: {{< var authors.tom >}} and {{< var authors.robert >}}
- [Chapter @sec-measurement]
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}s: {{< var authors.robert >}}, {{< var authors.tom >}}, and {{< var authors.rondeline >}}
- [Chapter @sec-design]
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}s: {{< var authors.nicholas >}} and {{< var authors.tom >}}
- [Chapter @sec-sampling]
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}s: {{< var authors.julie >}}, {{< var authors.tom >}}, and {{< var authors.maya >}}
- [Chapter @sec-prereg]
  - {{< var roles.w >}}: {{< var authors.tom >}}
  - {{< var roles.e >}}: {{< var authors.mike >}}
- [Chapter @sec-collection]
  - {{< var roles.c >}}s: {{< var authors.rondeline >}} and {{< var authors.mike >}}
  - {{< var roles.e >}}: {{< var authors.tom >}}
- [Chapter @sec-management]
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}: {{< var authors.tom >}}
- [Chapter @sec-viz]
  - {{< var roles.w >}}: {{< var authors.robert >}}
  - {{< var roles.e >}}s: {{< var authors.mike >}}, {{< var authors.tom >}}, and {{< var authors.mika >}}
- [Chapter @sec-writing]
  - {{< var roles.w >}}: {{< var authors.tom >}}
  - {{< var roles.e >}}: {{< var authors.mike >}}
- [Chapter @sec-meta]
  - {{< var roles.c >}}s: {{< var authors.nicholas >}} and {{< var authors.maya >}}
  - {{< var roles.e >}}s: {{< var authors.mike >}} and {{< var authors.tom >}}
- [Conclusion](#sec-conclusion)
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}: {{< var authors.tom >}}
- [Appendix @sec-instructors]
  - {{< var roles.w >}}: {{< var authors.julie >}}
  - {{< var roles.e >}}: {{< var authors.mike >}}
- [Appendix @sec-git]
  - {{< var roles.w >}}: {{< var authors.julie >}}
  - {{< var roles.e >}}: {{< var authors.mike >}}
- [Appendix @sec-rmarkdown]
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}: {{< var authors.julie >}}
- [Appendix @sec-tidyverse]
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}s: {{< var authors.julie >}} and {{< var authors.mika >}}
- [Appendix @sec-ggplot]
  - {{< var roles.w >}}: {{< var authors.mike >}}
  - {{< var roles.e >}}s: {{< var authors.julie >}} and {{< var authors.mika >}}
- Technical infrastructure
  - {{< var roles.d >}}s: {{< var authors.mika >}} and {{< var authors.natalie >}}

\section*{References}

\begin{CSLReferences}{1}{0}

\bibitem[\citeproctext]{ref-frank2012}
Frank, Michael C., and Rebecca Saxe. 2012. {``Teaching Replication.''}
\emph{Perspectives on Psychological Science} 7 (6): 600--604.
\url{https://doi.org/10.1177/1745691612460686}.

\bibitem[\citeproctext]{ref-hawkins2018}
Hawkins, Robert D., Eric N. Smith, Carolyn Au, Juan Miguel Arias, Rhia
Catapano, Eric Hermann, Martin Keil, et al. 2018. {``Improving the
Replicability of Psychological Science Through Pedagogy.''}
\emph{Advances in Methods and Practices in Psychological Science} 1 (1):
7--18. \url{https://doi.org/10.1177/2515245917740427}.

\end{CSLReferences}
