# Exploratory data analysis {#eda}

::: {.box .learning_goals}
* Explain how to evaluate the sensitivity of main analyses to modeling assumptions.
* Describe how modeling and data visualization support data analysis.
* Compare individual and item differences. 
:::

::: {.box .case_study}
Frank, Vul, & Johnson (2009) report a small subset of the many many analyses they ran on a very rich dataset. Luckily, the simplest analysis was the most important, and that one was replicable (Frank, Amso, and Johnson 2014).
:::

## Sensitivity Analysis

Exploring the sensitivity of your main analyses: covariates and exclusions


ManyAnalysts project - red card dataset (observational)
Poldrack neuroimaging manyanalysts


- Sensitivity analysis for parameters

::: {.box .interactive}
(TITLE) multi-verse analysis (effects of alternative choices)
:::


## Data exploration

General idea of "poking around" to find patterns in data that can inspire new ideas or perspectives on an experiment.

- Exploratory visualization

- Dimensionality reduction: exploratory factor analysis and PCA (when these techniques are useful, and roughly what they do; no mathematical exploration). Contrast with the use of these techniques in measurement and measure development. 

- Exploiting variation: individual differences and item differences. (Some discussion of psychometric models like item response theory as a way of exploring this variation).

## Exploratory modeling and theory-building

Exploratory modeling and model+data visualization: a continuous loop

- How to constrain and document exploratory analysis
- Devil and the deep blue sea post (Danielle Navarro)

<!-- Fancy stuff and when it is and isn’t appropriate -->

- Using cognitive models as predictors: an exciting way of making quantitative links between theory and data.

<!-- -   -->
